# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfChallengePlatformsAllOf")

model.instance <- PageOfChallengePlatformsAllOf$new()

test_that("challengePlatforms", {
  # tests for the property `challengePlatforms` (array[ChallengePlatform])
  # An array of ChallengePlatforms

  # uncomment below to test the property 
  #expect_equal(model.instance$`challengePlatforms`, "EXPECTED_RESULT")
})

