# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeAllOf")

model.instance <- ChallengeAllOf$new()

test_that("fullName", {
  # tests for the property `fullName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fullName`, "EXPECTED_RESULT")
})

test_that("ownerId", {
  # tests for the property `ownerId` (character)
  # The unique identifier of an account

  # uncomment below to test the property 
  #expect_equal(model.instance$`ownerId`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})

