# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgMembershipCreateResponse")

model.instance <- OrgMembershipCreateResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of the org membership

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

