# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponsePageMetadataPaging")

model.instance <- ResponsePageMetadataPaging$new()

test_that("next", {
  # tests for the property `next` (character)
  # Link to the next page of results

  # uncomment below to test the property 
  #expect_equal(model.instance$`next`, "EXPECTED_RESULT")
})

