# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationApi")

api.instance <- OrganizationApi$new()

test_that("CreateOrganization", {
  # tests for CreateOrganization
  # base path: https://rocc.org/api/v1
  # Create an organization
  # Create an organization with the specified account name
  # @param organization.create.request OrganizationCreateRequest 
  # @return [OrganizationCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllOrganizations", {
  # tests for DeleteAllOrganizations
  # base path: https://rocc.org/api/v1
  # Delete all organizations
  # Delete all organizations
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteOrganization", {
  # tests for DeleteOrganization
  # base path: https://rocc.org/api/v1
  # Delete an organization
  # Deletes the organization specified
  # @param organization.id character The unique identifier of the organization, either the user ID or account name
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrganization", {
  # tests for GetOrganization
  # base path: https://rocc.org/api/v1
  # Get an organization
  # Returns the organization specified
  # @param organization.id character The unique identifier of the organization, either the user ID or account name
  # @return [Organization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListOrganizations", {
  # tests for ListOrganizations
  # base path: https://rocc.org/api/v1
  # Get all organizations
  # Returns the organizations
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfOrganizations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

