# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HealthCheck")

model.instance <- HealthCheck$new()

test_that("status", {
  # tests for the property `status` (character)
  # Indicates whether the service status is acceptable or not

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

