# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserCreateResponse")

model.instance <- UserCreateResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of an account

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

