# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationCreateRequest")

model.instance <- OrganizationCreateRequest$new()

test_that("login", {
  # tests for the property `login` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`login`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # An email address

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("avatarUrl", {
  # tests for the property `avatarUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`avatarUrl`, "EXPECTED_RESULT")
})

test_that("websiteUrl", {
  # tests for the property `websiteUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`websiteUrl`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

