# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LocalAuthRequest")

model.instance <- LocalAuthRequest$new()

test_that("login", {
  # tests for the property `login` (character)
  # The user or organization account name

  # uncomment below to test the property 
  #expect_equal(model.instance$`login`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

