# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Account")

model.instance <- Account$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of an account

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("login", {
  # tests for the property `login` (character)
  # The user or organization account name

  # uncomment below to test the property 
  #expect_equal(model.instance$`login`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

