# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LocalAuthResponse")

model.instance <- LocalAuthResponse$new()

test_that("token", {
  # tests for the property `token` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

