# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfTagsAllOf")

model.instance <- PageOfTagsAllOf$new()

test_that("tags", {
  # tests for the property `tags` (array[Tag])
  # An array of Tags

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

