# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfGrants")

model.instance <- PageOfGrants$new()

test_that("offset", {
  # tests for the property `offset` (integer)
  # Index of the first result that must be returned

  # uncomment below to test the property 
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("limit", {
  # tests for the property `limit` (integer)
  # Maximum number of results returned

  # uncomment below to test the property 
  #expect_equal(model.instance$`limit`, "EXPECTED_RESULT")
})

test_that("paging", {
  # tests for the property `paging` (ResponsePageMetadataPaging)

  # uncomment below to test the property 
  #expect_equal(model.instance$`paging`, "EXPECTED_RESULT")
})

test_that("totalResults", {
  # tests for the property `totalResults` (integer)
  # Total number of results in the result set

  # uncomment below to test the property 
  #expect_equal(model.instance$`totalResults`, "EXPECTED_RESULT")
})

test_that("grants", {
  # tests for the property `grants` (array[Grant])
  # An array of Grants

  # uncomment below to test the property 
  #expect_equal(model.instance$`grants`, "EXPECTED_RESULT")
})

