# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfOrgMembershipsAllOf")

model.instance <- PageOfOrgMembershipsAllOf$new()

test_that("orgMemberships", {
  # tests for the property `orgMemberships` (array[OrgMembership])
  # An array of org memberships

  # uncomment below to test the property 
  #expect_equal(model.instance$`orgMemberships`, "EXPECTED_RESULT")
})

