# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccountApi")

api.instance <- AccountApi$new()

test_that("GetAccount", {
  # tests for GetAccount
  # base path: https://rocc.org/api/v1
  # Get an account
  # Returns the user or org account
  # @param login character The login of an account
  # @return [Account]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

