# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfChallengesAllOf")

model.instance <- PageOfChallengesAllOf$new()

test_that("challenges", {
  # tests for the property `challenges` (array[Challenge])
  # An array of Challenges

  # uncomment below to test the property 
  #expect_equal(model.instance$`challenges`, "EXPECTED_RESULT")
})

