# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthApi")

api.instance <- AuthApi$new()

test_that("AuthLocal", {
  # tests for AuthLocal
  # base path: https://rocc.org/api/v1
  # Authentify a local account
  # Authentify a local account with the specified credential
  # @param local.auth.request LocalAuthRequest 
  # @return [LocalAuthResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

