# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Challenge")

model.instance <- Challenge$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of the challenge

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the a challenge

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("displayName", {
  # tests for the property `displayName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`displayName`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A short description of the challenge

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("websiteUrl", {
  # tests for the property `websiteUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`websiteUrl`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (ChallengeStatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("startDate", {
  # tests for the property `startDate` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`startDate`, "EXPECTED_RESULT")
})

test_that("endDate", {
  # tests for the property `endDate` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`endDate`, "EXPECTED_RESULT")
})

test_that("platformId", {
  # tests for the property `platformId` (character)
  # The unique identifier of a challenge platform

  # uncomment below to test the property 
  #expect_equal(model.instance$`platformId`, "EXPECTED_RESULT")
})

test_that("topics", {
  # tests for the property `topics` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`topics`, "EXPECTED_RESULT")
})

test_that("doi", {
  # tests for the property `doi` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`doi`, "EXPECTED_RESULT")
})

test_that("fullName", {
  # tests for the property `fullName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fullName`, "EXPECTED_RESULT")
})

test_that("ownerId", {
  # tests for the property `ownerId` (character)
  # The unique identifier of an account

  # uncomment below to test the property 
  #expect_equal(model.instance$`ownerId`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})

