# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgMembershipApi")

api.instance <- OrgMembershipApi$new()

test_that("CreateOrgMembership", {
  # tests for CreateOrgMembership
  # base path: https://rocc.org/api/v1
  # Create an org membership
  # Create an org membership
  # @param org.membership.create.request OrgMembershipCreateRequest 
  # @return [OrgMembershipCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllOrgMemberships", {
  # tests for DeleteAllOrgMemberships
  # base path: https://rocc.org/api/v1
  # Delete all org memberships
  # Delete all org memberships
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteOrgMembership", {
  # tests for DeleteOrgMembership
  # base path: https://rocc.org/api/v1
  # Delete an org membership
  # Deletes the org membership specified
  # @param org.membership.id character The unique identifier of the org membership
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrgMembership", {
  # tests for GetOrgMembership
  # base path: https://rocc.org/api/v1
  # Get an org membership
  # Returns the org membership specified
  # @param org.membership.id character The unique identifier of the org membership
  # @return [OrgMembership]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListOrgMemberships", {
  # tests for ListOrgMemberships
  # base path: https://rocc.org/api/v1
  # List all the org memberships
  # Returns the org memberships
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @param org.id character An organization identifier used to filter the results (optional)
  # @param user.id character A user identifier used to filter the results (optional)
  # @return [PageOfOrgMemberships]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

