# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GrantCreateRequest")

model.instance <- GrantCreateRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The name of the grant

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

