# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserApi")

api.instance <- UserApi$new()

test_that("CreateUser", {
  # tests for CreateUser
  # base path: https://rocc.org/api/v1
  # Create a user
  # Create a user with the specified account name
  # @param user.create.request UserCreateRequest 
  # @return [UserCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllUsers", {
  # tests for DeleteAllUsers
  # base path: https://rocc.org/api/v1
  # Delete all users
  # Delete all users
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUser", {
  # tests for DeleteUser
  # base path: https://rocc.org/api/v1
  # Delete a user
  # Deletes the user specified
  # @param user.id character The unique identifier of the user, either the user account ID or login
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAuthenticatedUser", {
  # tests for GetAuthenticatedUser
  # base path: https://rocc.org/api/v1
  # Get the authenticated user
  # Get the authenticated user
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUser", {
  # tests for GetUser
  # base path: https://rocc.org/api/v1
  # Get a user
  # Returns the user specified
  # @param user.id character The unique identifier of the user, either the user account ID or login
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("IsStarredChallenge", {
  # tests for IsStarredChallenge
  # base path: https://rocc.org/api/v1
  # Check if a challenge is starred by the authenticated user
  # Check if a challenge is starred by the authenticated user
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListAuthenticatedUserOrganizations", {
  # tests for ListAuthenticatedUserOrganizations
  # base path: https://rocc.org/api/v1
  # List organizations of the authenticated user
  # Lists organizations the authenticated user belongs to.
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfOrganizations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListStarredChallenges", {
  # tests for ListStarredChallenges
  # base path: https://rocc.org/api/v1
  # List challenges starred by the authenticated user
  # Lists challenges the authenticated user has starred.
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfChallenges]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListUserOrganizations", {
  # tests for ListUserOrganizations
  # base path: https://rocc.org/api/v1
  # List orgsnizations of a user
  # Lists organizations a user belongs to.
  # @param user.id character The unique identifier of the user, either the user account ID or login
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfOrganizations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListUserStarredChallenges", {
  # tests for ListUserStarredChallenges
  # base path: https://rocc.org/api/v1
  # List challenges starred by a user
  # Lists challenges a user has starred.
  # @param user.id character The unique identifier of the user, either the user account ID or login
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfChallenges]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListUsers", {
  # tests for ListUsers
  # base path: https://rocc.org/api/v1
  # Get all users
  # Returns the users
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfUsers]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("StarChallenge", {
  # tests for StarChallenge
  # base path: https://rocc.org/api/v1
  # Star a challenge for the authenticated user
  # Star a challenge for the authenticated user
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UnstarChallenge", {
  # tests for UnstarChallenge
  # base path: https://rocc.org/api/v1
  # Unstar a challenge for the authenticated user
  # Unstar a challenge for the authenticated user
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

