# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HealthCheckApi")

api.instance <- HealthCheckApi$new()

test_that("GetHealthCheck", {
  # tests for GetHealthCheck
  # base path: https://rocc.org/api/v1
  # Get health check information
  # Get information about the health of the service
  # @return [HealthCheck]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

