# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeReadme")

model.instance <- ChallengeReadme$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of a challenge README

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("text", {
  # tests for the property `text` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`text`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})

