# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgMembershipCreateRequest")

model.instance <- OrgMembershipCreateRequest$new()

test_that("state", {
  # tests for the property `state` (character)
  # The state of the member in the organization. The &#x60;pending&#x60; state indicates the user has not yet accepted an invitation.

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (character)
  # The user&#39;s membership type in the organization.

  # uncomment below to test the property 
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("organizationId", {
  # tests for the property `organizationId` (character)
  # The unique identifier of an organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`organizationId`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (character)
  # The unique identifier of a user

  # uncomment below to test the property 
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

