# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengePlatformCreateRequest")

model.instance <- ChallengePlatformCreateRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The name of the challenge platform

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("displayName", {
  # tests for the property `displayName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`displayName`, "EXPECTED_RESULT")
})

test_that("websiteUrl", {
  # tests for the property `websiteUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`websiteUrl`, "EXPECTED_RESULT")
})

test_that("avatarUrl", {
  # tests for the property `avatarUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`avatarUrl`, "EXPECTED_RESULT")
})

