# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GrantApi")

api.instance <- GrantApi$new()

test_that("CreateGrant", {
  # tests for CreateGrant
  # base path: https://rocc.org/api/v1
  # Create a grant
  # Create a grant with the specified name
  # @param grant.create.request GrantCreateRequest 
  # @return [GrantCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllGrants", {
  # tests for DeleteAllGrants
  # base path: https://rocc.org/api/v1
  # Delete all grants
  # Delete all grants
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteGrant", {
  # tests for DeleteGrant
  # base path: https://rocc.org/api/v1
  # Delete a grant
  # Deletes the grant specified
  # @param grant.id character The ID of the grant that is being created
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGrant", {
  # tests for GetGrant
  # base path: https://rocc.org/api/v1
  # Get a grant
  # Returns the grant specified
  # @param grant.id character The ID of the grant that is being created
  # @return [Grant]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListGrants", {
  # tests for ListGrants
  # base path: https://rocc.org/api/v1
  # Get all grants
  # Returns the grants
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfGrants]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

