# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfUsersAllOf")

model.instance <- PageOfUsersAllOf$new()

test_that("users", {
  # tests for the property `users` (array[User])
  # An array of Users

  # uncomment below to test the property 
  #expect_equal(model.instance$`users`, "EXPECTED_RESULT")
})

