# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfGrantsAllOf")

model.instance <- PageOfGrantsAllOf$new()

test_that("grants", {
  # tests for the property `grants` (array[Grant])
  # An array of Grants

  # uncomment below to test the property 
  #expect_equal(model.instance$`grants`, "EXPECTED_RESULT")
})

