# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengePlatform")

model.instance <- ChallengePlatform$new()

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of a challenge platform

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the challenge platform

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("displayName", {
  # tests for the property `displayName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`displayName`, "EXPECTED_RESULT")
})

test_that("websiteUrl", {
  # tests for the property `websiteUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`websiteUrl`, "EXPECTED_RESULT")
})

test_that("avatarUrl", {
  # tests for the property `avatarUrl` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`avatarUrl`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})

