# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageOfOrganizationsAllOf")

model.instance <- PageOfOrganizationsAllOf$new()

test_that("organizations", {
  # tests for the property `organizations` (array[Organization])
  # An array of Organizations

  # uncomment below to test the property 
  #expect_equal(model.instance$`organizations`, "EXPECTED_RESULT")
})

