# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeApi")

api.instance <- ChallengeApi$new()

test_that("CreateChallenge", {
  # tests for CreateChallenge
  # base path: https://rocc.org/api/v1
  # Add a challenge
  # Adds a challenge
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.create.request ChallengeCreateRequest 
  # @return [ChallengeCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateChallengeOrganizer", {
  # tests for CreateChallengeOrganizer
  # base path: https://rocc.org/api/v1
  # Create a challenge organizer
  # Create a challenge organizer
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @param challenge.organizer.create.request ChallengeOrganizerCreateRequest 
  # @return [ChallengeOrganizerCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllChallenges", {
  # tests for DeleteAllChallenges
  # base path: https://rocc.org/api/v1
  # Delete all challenges
  # Delete all challenges
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteChallenge", {
  # tests for DeleteChallenge
  # base path: https://rocc.org/api/v1
  # Delete a challenge
  # Deletes the challenge specified
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteChallengeOrganizer", {
  # tests for DeleteChallengeOrganizer
  # base path: https://rocc.org/api/v1
  # Delete a challenge organizer
  # Deletes the challenge organizer specified
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @param organizer.id character The identifier of the challenge organizer
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetChallenge", {
  # tests for GetChallenge
  # base path: https://rocc.org/api/v1
  # Get a challenge
  # Returns the challenge specified
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [Challenge]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetChallengeReadme", {
  # tests for GetChallengeReadme
  # base path: https://rocc.org/api/v1
  # Get a challenge README
  # Returns the challenge README specified
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [ChallengeReadme]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListAccountChallenges", {
  # tests for ListAccountChallenges
  # base path: https://rocc.org/api/v1
  # List all the challenges owned by the specified account
  # List all the challenges owned by the specified account
  # @param account.name character The name of the account that owns the challenge
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfChallenges]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChallengeOrganizers", {
  # tests for ListChallengeOrganizers
  # base path: https://rocc.org/api/v1
  # List organizers
  # Lists the organizers of the challenge.
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [ChallengeOrganizerList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChallengeStargazers", {
  # tests for ListChallengeStargazers
  # base path: https://rocc.org/api/v1
  # List stargazers
  # Lists the people that have starred the challenge.
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfUsers]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChallengeTopics", {
  # tests for ListChallengeTopics
  # base path: https://rocc.org/api/v1
  # List stargazers
  # Lists the challenge topics.
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @return [ArrayOfTopics]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChallenges", {
  # tests for ListChallenges
  # base path: https://rocc.org/api/v1
  # List all the challenges
  # Returns all the challenges
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @param sort character Property used to sort the results that must be returned (optional)
  # @param direction character Can be either `asc` or `desc`. Ignored without `sort` parameter. (optional)
  # @param search.terms character A string of search terms used to filter the results (optional)
  # @param topics array[character] Array of topics used to filter the results (optional)
  # @param status array[ChallengeStatus] Array of challenge status used to filter the results (optional)
  # @param platform.ids array[character] Array of challenge platform ids used to filter the results (optional)
  # @param start.date.range DateRange Return challenges that start during the date range specified (optional)
  # @return [PageOfChallenges]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateChallengeReadme", {
  # tests for UpdateChallengeReadme
  # base path: https://rocc.org/api/v1
  # Update a challenge README
  # Update a challenge README
  # @param account.name character The name of the account that owns the challenge
  # @param challenge.name character The name of the challenge
  # @param challenge.readme.update.request ChallengeReadmeUpdateRequest 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

