# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeOrganizerList")

model.instance <- ChallengeOrganizerList$new()

test_that("challengeOrganizers", {
  # tests for the property `challengeOrganizers` (array[ChallengeOrganizer])
  # A list of ChallengeOrganizers

  # uncomment below to test the property 
  #expect_equal(model.instance$`challengeOrganizers`, "EXPECTED_RESULT")
})

