# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengePlatformApi")

api.instance <- ChallengePlatformApi$new()

test_that("CreateChallengePlatform", {
  # tests for CreateChallengePlatform
  # base path: https://rocc.org/api/v1
  # Create a challenge platform
  # Create a challenge platform with the specified ID
  # @param challenge.platform.create.request ChallengePlatformCreateRequest 
  # @return [ChallengePlatformCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAllChallengePlatforms", {
  # tests for DeleteAllChallengePlatforms
  # base path: https://rocc.org/api/v1
  # Delete all challenge platforms
  # Delete all challenge platforms
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteChallengePlatform", {
  # tests for DeleteChallengePlatform
  # base path: https://rocc.org/api/v1
  # Delete a challenge platform
  # Deletes the challenge platform specified
  # @param challenge.platform.id character The unique identifier of the challenge platform
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetChallengePlatform", {
  # tests for GetChallengePlatform
  # base path: https://rocc.org/api/v1
  # Get a challenge platform
  # Returns the challenge platform specified
  # @param challenge.platform.id character The unique identifier of the challenge platform
  # @return [ChallengePlatform]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChallengePlatforms", {
  # tests for ListChallengePlatforms
  # base path: https://rocc.org/api/v1
  # Get all challenge platforms
  # Returns the challenge platforms
  # @param limit integer Maximum number of results returned (optional)
  # @param offset integer Index of the first result that must be returned (optional)
  # @return [PageOfChallengePlatforms]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

