# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DateRange")

model.instance <- DateRange$new()

test_that("start", {
  # tests for the property `start` (character)
  # Start date of the date range

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (character)
  # End date of the date range

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

