# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TagCreateRequest")

model.instance <- TagCreateRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The name of a tag

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

