# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayOfTopics")

model.instance <- ArrayOfTopics$new()

test_that("topics", {
  # tests for the property `topics` (array[character])
  # An array of Topics

  # uncomment below to test the property 
  #expect_equal(model.instance$`topics`, "EXPECTED_RESULT")
})

