# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Account
#'
#' @description Account Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field login  character 
#'
#' @field type  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Account <- R6::R6Class(
  'Account',
  public = list(
    `id` = NULL,
    `login` = NULL,
    `type` = NULL,
    initialize = function(
        `id`, `login`, `type`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      AccountObject <- list()
      if (!is.null(self$`id`)) {
        AccountObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`login`)) {
        AccountObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`type`)) {
        AccountObject[['type']] <-
          self$`type`
      }

      AccountObject
    },
    fromJSON = function(AccountJson) {
      AccountObject <- jsonlite::fromJSON(AccountJson)
      if (!is.null(AccountObject$`id`)) {
        self$`id` <- AccountObject$`id`
      }
      if (!is.null(AccountObject$`login`)) {
        self$`login` <- AccountObject$`login`
      }
      if (!is.null(AccountObject$`type`)) {
        self$`type` <- AccountObject$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccountJson) {
      AccountObject <- jsonlite::fromJSON(AccountJson)
      self$`id` <- AccountObject$`id`
      self$`login` <- AccountObject$`login`
      self$`type` <- AccountObject$`type`
      self
    }
  )
)
