# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayOfTopics
#'
#' @description ArrayOfTopics Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field topics  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayOfTopics <- R6::R6Class(
  'ArrayOfTopics',
  public = list(
    `topics` = NULL,
    initialize = function(
        `topics`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`topics`)) {
        stopifnot(is.vector(`topics`), length(`topics`) != 0)
        sapply(`topics`, function(x) stopifnot(is.character(x)))
        self$`topics` <- `topics`
      }
    },
    toJSON = function() {
      ArrayOfTopicsObject <- list()
      if (!is.null(self$`topics`)) {
        ArrayOfTopicsObject[['topics']] <-
          self$`topics`
      }

      ArrayOfTopicsObject
    },
    fromJSON = function(ArrayOfTopicsJson) {
      ArrayOfTopicsObject <- jsonlite::fromJSON(ArrayOfTopicsJson)
      if (!is.null(ArrayOfTopicsObject$`topics`)) {
        self$`topics` <- ApiClient$new()$deserializeObj(ArrayOfTopicsObject$`topics`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`topics`)) {
        sprintf(
        '"topics":
           [%s]
        ',
        paste(unlist(lapply(self$`topics`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayOfTopicsJson) {
      ArrayOfTopicsObject <- jsonlite::fromJSON(ArrayOfTopicsJson)
      self$`topics` <- ApiClient$new()$deserializeObj(ArrayOfTopicsObject$`topics`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)
