# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeCreateRequest
#'
#' @description ChallengeCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field displayName  character [optional]
#'
#' @field description  character 
#'
#' @field websiteUrl  character [optional]
#'
#' @field status  \link{ChallengeStatus} [optional]
#'
#' @field startDate  character [optional]
#'
#' @field endDate  character [optional]
#'
#' @field platformId  character [optional]
#'
#' @field topics  list( character ) [optional]
#'
#' @field doi  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeCreateRequest <- R6::R6Class(
  'ChallengeCreateRequest',
  public = list(
    `name` = NULL,
    `displayName` = NULL,
    `description` = NULL,
    `websiteUrl` = NULL,
    `status` = NULL,
    `startDate` = NULL,
    `endDate` = NULL,
    `platformId` = NULL,
    `topics` = NULL,
    `doi` = NULL,
    initialize = function(
        `name`, `description`, `displayName`=NULL, `websiteUrl`=NULL, `status`=NULL, `startDate`=NULL, `endDate`=NULL, `platformId`=NULL, `topics`=NULL, `doi`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`displayName`)) {
        stopifnot(is.character(`displayName`), length(`displayName`) == 1)
        self$`displayName` <- `displayName`
      }
      if (!is.null(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!is.null(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!is.null(`startDate`)) {
        stopifnot(is.character(`startDate`), length(`startDate`) == 1)
        self$`startDate` <- `startDate`
      }
      if (!is.null(`endDate`)) {
        stopifnot(is.character(`endDate`), length(`endDate`) == 1)
        self$`endDate` <- `endDate`
      }
      if (!is.null(`platformId`)) {
        stopifnot(is.character(`platformId`), length(`platformId`) == 1)
        self$`platformId` <- `platformId`
      }
      if (!is.null(`topics`)) {
        stopifnot(is.vector(`topics`), length(`topics`) != 0)
        sapply(`topics`, function(x) stopifnot(is.character(x)))
        self$`topics` <- `topics`
      }
      if (!is.null(`doi`)) {
        stopifnot(is.character(`doi`), length(`doi`) == 1)
        self$`doi` <- `doi`
      }
    },
    toJSON = function() {
      ChallengeCreateRequestObject <- list()
      if (!is.null(self$`name`)) {
        ChallengeCreateRequestObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`displayName`)) {
        ChallengeCreateRequestObject[['displayName']] <-
          self$`displayName`
      }
      if (!is.null(self$`description`)) {
        ChallengeCreateRequestObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`websiteUrl`)) {
        ChallengeCreateRequestObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`status`)) {
        ChallengeCreateRequestObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`startDate`)) {
        ChallengeCreateRequestObject[['startDate']] <-
          self$`startDate`
      }
      if (!is.null(self$`endDate`)) {
        ChallengeCreateRequestObject[['endDate']] <-
          self$`endDate`
      }
      if (!is.null(self$`platformId`)) {
        ChallengeCreateRequestObject[['platformId']] <-
          self$`platformId`
      }
      if (!is.null(self$`topics`)) {
        ChallengeCreateRequestObject[['topics']] <-
          self$`topics`
      }
      if (!is.null(self$`doi`)) {
        ChallengeCreateRequestObject[['doi']] <-
          self$`doi`
      }

      ChallengeCreateRequestObject
    },
    fromJSON = function(ChallengeCreateRequestJson) {
      ChallengeCreateRequestObject <- jsonlite::fromJSON(ChallengeCreateRequestJson)
      if (!is.null(ChallengeCreateRequestObject$`name`)) {
        self$`name` <- ChallengeCreateRequestObject$`name`
      }
      if (!is.null(ChallengeCreateRequestObject$`displayName`)) {
        self$`displayName` <- ChallengeCreateRequestObject$`displayName`
      }
      if (!is.null(ChallengeCreateRequestObject$`description`)) {
        self$`description` <- ChallengeCreateRequestObject$`description`
      }
      if (!is.null(ChallengeCreateRequestObject$`websiteUrl`)) {
        self$`websiteUrl` <- ChallengeCreateRequestObject$`websiteUrl`
      }
      if (!is.null(ChallengeCreateRequestObject$`status`)) {
        statusObject <- ChallengeStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(ChallengeCreateRequestObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(ChallengeCreateRequestObject$`startDate`)) {
        self$`startDate` <- ChallengeCreateRequestObject$`startDate`
      }
      if (!is.null(ChallengeCreateRequestObject$`endDate`)) {
        self$`endDate` <- ChallengeCreateRequestObject$`endDate`
      }
      if (!is.null(ChallengeCreateRequestObject$`platformId`)) {
        self$`platformId` <- ChallengeCreateRequestObject$`platformId`
      }
      if (!is.null(ChallengeCreateRequestObject$`topics`)) {
        self$`topics` <- ApiClient$new()$deserializeObj(ChallengeCreateRequestObject$`topics`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ChallengeCreateRequestObject$`doi`)) {
        self$`doi` <- ChallengeCreateRequestObject$`doi`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`displayName`)) {
        sprintf(
        '"displayName":
          "%s"
                ',
        self$`displayName`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`startDate`)) {
        sprintf(
        '"startDate":
          "%s"
                ',
        self$`startDate`
        )},
        if (!is.null(self$`endDate`)) {
        sprintf(
        '"endDate":
          "%s"
                ',
        self$`endDate`
        )},
        if (!is.null(self$`platformId`)) {
        sprintf(
        '"platformId":
          "%s"
                ',
        self$`platformId`
        )},
        if (!is.null(self$`topics`)) {
        sprintf(
        '"topics":
           [%s]
        ',
        paste(unlist(lapply(self$`topics`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`doi`)) {
        sprintf(
        '"doi":
          "%s"
                ',
        self$`doi`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeCreateRequestJson) {
      ChallengeCreateRequestObject <- jsonlite::fromJSON(ChallengeCreateRequestJson)
      self$`name` <- ChallengeCreateRequestObject$`name`
      self$`displayName` <- ChallengeCreateRequestObject$`displayName`
      self$`description` <- ChallengeCreateRequestObject$`description`
      self$`websiteUrl` <- ChallengeCreateRequestObject$`websiteUrl`
      self$`status` <- ChallengeStatus$new()$fromJSON(jsonlite::toJSON(ChallengeCreateRequestObject$status, auto_unbox = TRUE, digits = NA))
      self$`startDate` <- ChallengeCreateRequestObject$`startDate`
      self$`endDate` <- ChallengeCreateRequestObject$`endDate`
      self$`platformId` <- ChallengeCreateRequestObject$`platformId`
      self$`topics` <- ApiClient$new()$deserializeObj(ChallengeCreateRequestObject$`topics`, "array[character]", loadNamespace("openapi"))
      self$`doi` <- ChallengeCreateRequestObject$`doi`
      self
    }
  )
)
