# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeReadmeAllOf
#'
#' @description ChallengeReadmeAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeReadmeAllOf <- R6::R6Class(
  'ChallengeReadmeAllOf',
  public = list(
    `createdAt` = NULL,
    `updatedAt` = NULL,
    initialize = function(
        `createdAt`, `updatedAt`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
    },
    toJSON = function() {
      ChallengeReadmeAllOfObject <- list()
      if (!is.null(self$`createdAt`)) {
        ChallengeReadmeAllOfObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        ChallengeReadmeAllOfObject[['updatedAt']] <-
          self$`updatedAt`
      }

      ChallengeReadmeAllOfObject
    },
    fromJSON = function(ChallengeReadmeAllOfJson) {
      ChallengeReadmeAllOfObject <- jsonlite::fromJSON(ChallengeReadmeAllOfJson)
      if (!is.null(ChallengeReadmeAllOfObject$`createdAt`)) {
        self$`createdAt` <- ChallengeReadmeAllOfObject$`createdAt`
      }
      if (!is.null(ChallengeReadmeAllOfObject$`updatedAt`)) {
        self$`updatedAt` <- ChallengeReadmeAllOfObject$`updatedAt`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeReadmeAllOfJson) {
      ChallengeReadmeAllOfObject <- jsonlite::fromJSON(ChallengeReadmeAllOfJson)
      self$`createdAt` <- ChallengeReadmeAllOfObject$`createdAt`
      self$`updatedAt` <- ChallengeReadmeAllOfObject$`updatedAt`
      self
    }
  )
)
