# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeOrganizerCreateRequest
#'
#' @description ChallengeOrganizerCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field login  character [optional]
#'
#' @field roles  list( \link{ChallengeOrganizerRole} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeOrganizerCreateRequest <- R6::R6Class(
  'ChallengeOrganizerCreateRequest',
  public = list(
    `name` = NULL,
    `login` = NULL,
    `roles` = NULL,
    initialize = function(
        `name`, `login`=NULL, `roles`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!is.null(`roles`)) {
        stopifnot(is.vector(`roles`), length(`roles`) != 0)
        sapply(`roles`, function(x) stopifnot(R6::is.R6(x)))
        self$`roles` <- `roles`
      }
    },
    toJSON = function() {
      ChallengeOrganizerCreateRequestObject <- list()
      if (!is.null(self$`name`)) {
        ChallengeOrganizerCreateRequestObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`login`)) {
        ChallengeOrganizerCreateRequestObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`roles`)) {
        ChallengeOrganizerCreateRequestObject[['roles']] <-
          lapply(self$`roles`, function(x) x$toJSON())
      }

      ChallengeOrganizerCreateRequestObject
    },
    fromJSON = function(ChallengeOrganizerCreateRequestJson) {
      ChallengeOrganizerCreateRequestObject <- jsonlite::fromJSON(ChallengeOrganizerCreateRequestJson)
      if (!is.null(ChallengeOrganizerCreateRequestObject$`name`)) {
        self$`name` <- ChallengeOrganizerCreateRequestObject$`name`
      }
      if (!is.null(ChallengeOrganizerCreateRequestObject$`login`)) {
        self$`login` <- ChallengeOrganizerCreateRequestObject$`login`
      }
      if (!is.null(ChallengeOrganizerCreateRequestObject$`roles`)) {
        self$`roles` <- ApiClient$new()$deserializeObj(ChallengeOrganizerCreateRequestObject$`roles`, "array[ChallengeOrganizerRole]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`roles`)) {
        sprintf(
        '"roles":
        [%s]
',
        paste(sapply(self$`roles`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeOrganizerCreateRequestJson) {
      ChallengeOrganizerCreateRequestObject <- jsonlite::fromJSON(ChallengeOrganizerCreateRequestJson)
      self$`name` <- ChallengeOrganizerCreateRequestObject$`name`
      self$`login` <- ChallengeOrganizerCreateRequestObject$`login`
      self$`roles` <- ApiClient$new()$deserializeObj(ChallengeOrganizerCreateRequestObject$`roles`, "array[ChallengeOrganizerRole]", loadNamespace("openapi"))
      self
    }
  )
)
