# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengePlatformCreateRequest
#'
#' @description ChallengePlatformCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field displayName  character 
#'
#' @field websiteUrl  character 
#'
#' @field avatarUrl  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengePlatformCreateRequest <- R6::R6Class(
  'ChallengePlatformCreateRequest',
  public = list(
    `name` = NULL,
    `displayName` = NULL,
    `websiteUrl` = NULL,
    `avatarUrl` = NULL,
    initialize = function(
        `name`, `displayName`, `websiteUrl`, `avatarUrl`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`displayName`)) {
        stopifnot(is.character(`displayName`), length(`displayName`) == 1)
        self$`displayName` <- `displayName`
      }
      if (!missing(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!missing(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
    },
    toJSON = function() {
      ChallengePlatformCreateRequestObject <- list()
      if (!is.null(self$`name`)) {
        ChallengePlatformCreateRequestObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`displayName`)) {
        ChallengePlatformCreateRequestObject[['displayName']] <-
          self$`displayName`
      }
      if (!is.null(self$`websiteUrl`)) {
        ChallengePlatformCreateRequestObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`avatarUrl`)) {
        ChallengePlatformCreateRequestObject[['avatarUrl']] <-
          self$`avatarUrl`
      }

      ChallengePlatformCreateRequestObject
    },
    fromJSON = function(ChallengePlatformCreateRequestJson) {
      ChallengePlatformCreateRequestObject <- jsonlite::fromJSON(ChallengePlatformCreateRequestJson)
      if (!is.null(ChallengePlatformCreateRequestObject$`name`)) {
        self$`name` <- ChallengePlatformCreateRequestObject$`name`
      }
      if (!is.null(ChallengePlatformCreateRequestObject$`displayName`)) {
        self$`displayName` <- ChallengePlatformCreateRequestObject$`displayName`
      }
      if (!is.null(ChallengePlatformCreateRequestObject$`websiteUrl`)) {
        self$`websiteUrl` <- ChallengePlatformCreateRequestObject$`websiteUrl`
      }
      if (!is.null(ChallengePlatformCreateRequestObject$`avatarUrl`)) {
        self$`avatarUrl` <- ChallengePlatformCreateRequestObject$`avatarUrl`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`displayName`)) {
        sprintf(
        '"displayName":
          "%s"
                ',
        self$`displayName`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengePlatformCreateRequestJson) {
      ChallengePlatformCreateRequestObject <- jsonlite::fromJSON(ChallengePlatformCreateRequestJson)
      self$`name` <- ChallengePlatformCreateRequestObject$`name`
      self$`displayName` <- ChallengePlatformCreateRequestObject$`displayName`
      self$`websiteUrl` <- ChallengePlatformCreateRequestObject$`websiteUrl`
      self$`avatarUrl` <- ChallengePlatformCreateRequestObject$`avatarUrl`
      self
    }
  )
)
