# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Challenge
#'
#' @description Challenge Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field name  character 
#'
#' @field displayName  character [optional]
#'
#' @field description  character 
#'
#' @field websiteUrl  character [optional]
#'
#' @field status  \link{ChallengeStatus} [optional]
#'
#' @field startDate  character [optional]
#'
#' @field endDate  character [optional]
#'
#' @field platformId  character [optional]
#'
#' @field topics  list( character ) [optional]
#'
#' @field doi  character [optional]
#'
#' @field fullName  character 
#'
#' @field ownerId  character 
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Challenge <- R6::R6Class(
  'Challenge',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `displayName` = NULL,
    `description` = NULL,
    `websiteUrl` = NULL,
    `status` = NULL,
    `startDate` = NULL,
    `endDate` = NULL,
    `platformId` = NULL,
    `topics` = NULL,
    `doi` = NULL,
    `fullName` = NULL,
    `ownerId` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    initialize = function(
        `id`, `name`, `description`, `fullName`, `ownerId`, `createdAt`, `updatedAt`, `displayName`=NULL, `websiteUrl`=NULL, `status`=NULL, `startDate`=NULL, `endDate`=NULL, `platformId`=NULL, `topics`=NULL, `doi`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`fullName`)) {
        stopifnot(is.character(`fullName`), length(`fullName`) == 1)
        self$`fullName` <- `fullName`
      }
      if (!missing(`ownerId`)) {
        stopifnot(is.character(`ownerId`), length(`ownerId`) == 1)
        self$`ownerId` <- `ownerId`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!is.null(`displayName`)) {
        stopifnot(is.character(`displayName`), length(`displayName`) == 1)
        self$`displayName` <- `displayName`
      }
      if (!is.null(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!is.null(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!is.null(`startDate`)) {
        stopifnot(is.character(`startDate`), length(`startDate`) == 1)
        self$`startDate` <- `startDate`
      }
      if (!is.null(`endDate`)) {
        stopifnot(is.character(`endDate`), length(`endDate`) == 1)
        self$`endDate` <- `endDate`
      }
      if (!is.null(`platformId`)) {
        stopifnot(is.character(`platformId`), length(`platformId`) == 1)
        self$`platformId` <- `platformId`
      }
      if (!is.null(`topics`)) {
        stopifnot(is.vector(`topics`), length(`topics`) != 0)
        sapply(`topics`, function(x) stopifnot(is.character(x)))
        self$`topics` <- `topics`
      }
      if (!is.null(`doi`)) {
        stopifnot(is.character(`doi`), length(`doi`) == 1)
        self$`doi` <- `doi`
      }
    },
    toJSON = function() {
      ChallengeObject <- list()
      if (!is.null(self$`id`)) {
        ChallengeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ChallengeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`displayName`)) {
        ChallengeObject[['displayName']] <-
          self$`displayName`
      }
      if (!is.null(self$`description`)) {
        ChallengeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`websiteUrl`)) {
        ChallengeObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`status`)) {
        ChallengeObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`startDate`)) {
        ChallengeObject[['startDate']] <-
          self$`startDate`
      }
      if (!is.null(self$`endDate`)) {
        ChallengeObject[['endDate']] <-
          self$`endDate`
      }
      if (!is.null(self$`platformId`)) {
        ChallengeObject[['platformId']] <-
          self$`platformId`
      }
      if (!is.null(self$`topics`)) {
        ChallengeObject[['topics']] <-
          self$`topics`
      }
      if (!is.null(self$`doi`)) {
        ChallengeObject[['doi']] <-
          self$`doi`
      }
      if (!is.null(self$`fullName`)) {
        ChallengeObject[['fullName']] <-
          self$`fullName`
      }
      if (!is.null(self$`ownerId`)) {
        ChallengeObject[['ownerId']] <-
          self$`ownerId`
      }
      if (!is.null(self$`createdAt`)) {
        ChallengeObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        ChallengeObject[['updatedAt']] <-
          self$`updatedAt`
      }

      ChallengeObject
    },
    fromJSON = function(ChallengeJson) {
      ChallengeObject <- jsonlite::fromJSON(ChallengeJson)
      if (!is.null(ChallengeObject$`id`)) {
        self$`id` <- ChallengeObject$`id`
      }
      if (!is.null(ChallengeObject$`name`)) {
        self$`name` <- ChallengeObject$`name`
      }
      if (!is.null(ChallengeObject$`displayName`)) {
        self$`displayName` <- ChallengeObject$`displayName`
      }
      if (!is.null(ChallengeObject$`description`)) {
        self$`description` <- ChallengeObject$`description`
      }
      if (!is.null(ChallengeObject$`websiteUrl`)) {
        self$`websiteUrl` <- ChallengeObject$`websiteUrl`
      }
      if (!is.null(ChallengeObject$`status`)) {
        statusObject <- ChallengeStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(ChallengeObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(ChallengeObject$`startDate`)) {
        self$`startDate` <- ChallengeObject$`startDate`
      }
      if (!is.null(ChallengeObject$`endDate`)) {
        self$`endDate` <- ChallengeObject$`endDate`
      }
      if (!is.null(ChallengeObject$`platformId`)) {
        self$`platformId` <- ChallengeObject$`platformId`
      }
      if (!is.null(ChallengeObject$`topics`)) {
        self$`topics` <- ApiClient$new()$deserializeObj(ChallengeObject$`topics`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ChallengeObject$`doi`)) {
        self$`doi` <- ChallengeObject$`doi`
      }
      if (!is.null(ChallengeObject$`fullName`)) {
        self$`fullName` <- ChallengeObject$`fullName`
      }
      if (!is.null(ChallengeObject$`ownerId`)) {
        self$`ownerId` <- ChallengeObject$`ownerId`
      }
      if (!is.null(ChallengeObject$`createdAt`)) {
        self$`createdAt` <- ChallengeObject$`createdAt`
      }
      if (!is.null(ChallengeObject$`updatedAt`)) {
        self$`updatedAt` <- ChallengeObject$`updatedAt`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`displayName`)) {
        sprintf(
        '"displayName":
          "%s"
                ',
        self$`displayName`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`startDate`)) {
        sprintf(
        '"startDate":
          "%s"
                ',
        self$`startDate`
        )},
        if (!is.null(self$`endDate`)) {
        sprintf(
        '"endDate":
          "%s"
                ',
        self$`endDate`
        )},
        if (!is.null(self$`platformId`)) {
        sprintf(
        '"platformId":
          "%s"
                ',
        self$`platformId`
        )},
        if (!is.null(self$`topics`)) {
        sprintf(
        '"topics":
           [%s]
        ',
        paste(unlist(lapply(self$`topics`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`doi`)) {
        sprintf(
        '"doi":
          "%s"
                ',
        self$`doi`
        )},
        if (!is.null(self$`fullName`)) {
        sprintf(
        '"fullName":
          "%s"
                ',
        self$`fullName`
        )},
        if (!is.null(self$`ownerId`)) {
        sprintf(
        '"ownerId":
          "%s"
                ',
        self$`ownerId`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeJson) {
      ChallengeObject <- jsonlite::fromJSON(ChallengeJson)
      self$`id` <- ChallengeObject$`id`
      self$`name` <- ChallengeObject$`name`
      self$`displayName` <- ChallengeObject$`displayName`
      self$`description` <- ChallengeObject$`description`
      self$`websiteUrl` <- ChallengeObject$`websiteUrl`
      self$`status` <- ChallengeStatus$new()$fromJSON(jsonlite::toJSON(ChallengeObject$status, auto_unbox = TRUE, digits = NA))
      self$`startDate` <- ChallengeObject$`startDate`
      self$`endDate` <- ChallengeObject$`endDate`
      self$`platformId` <- ChallengeObject$`platformId`
      self$`topics` <- ApiClient$new()$deserializeObj(ChallengeObject$`topics`, "array[character]", loadNamespace("openapi"))
      self$`doi` <- ChallengeObject$`doi`
      self$`fullName` <- ChallengeObject$`fullName`
      self$`ownerId` <- ChallengeObject$`ownerId`
      self$`createdAt` <- ChallengeObject$`createdAt`
      self$`updatedAt` <- ChallengeObject$`updatedAt`
      self
    }
  )
)
