# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeReadmeUpdateRequest
#'
#' @description ChallengeReadmeUpdateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field text  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeReadmeUpdateRequest <- R6::R6Class(
  'ChallengeReadmeUpdateRequest',
  public = list(
    `text` = NULL,
    initialize = function(
        `text`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`text`)) {
        stopifnot(is.character(`text`), length(`text`) == 1)
        self$`text` <- `text`
      }
    },
    toJSON = function() {
      ChallengeReadmeUpdateRequestObject <- list()
      if (!is.null(self$`text`)) {
        ChallengeReadmeUpdateRequestObject[['text']] <-
          self$`text`
      }

      ChallengeReadmeUpdateRequestObject
    },
    fromJSON = function(ChallengeReadmeUpdateRequestJson) {
      ChallengeReadmeUpdateRequestObject <- jsonlite::fromJSON(ChallengeReadmeUpdateRequestJson)
      if (!is.null(ChallengeReadmeUpdateRequestObject$`text`)) {
        self$`text` <- ChallengeReadmeUpdateRequestObject$`text`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`text`)) {
        sprintf(
        '"text":
          "%s"
                ',
        self$`text`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeReadmeUpdateRequestJson) {
      ChallengeReadmeUpdateRequestObject <- jsonlite::fromJSON(ChallengeReadmeUpdateRequestJson)
      self$`text` <- ChallengeReadmeUpdateRequestObject$`text`
      self
    }
  )
)
