# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Challenge operations
#' @description openapi.Challenge
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateChallenge } \emph{ Add a challenge }
#' Adds a challenge
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.create.request \link{ChallengeCreateRequest}
#' \item \emph{ @returnType } \link{ChallengeCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : ChallengeCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ CreateChallengeOrganizer } \emph{ Create a challenge organizer }
#' Create a challenge organizer
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @param } challenge.organizer.create.request \link{ChallengeOrganizerCreateRequest}
#' \item \emph{ @returnType } \link{ChallengeOrganizerCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : ChallengeOrganizerCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteAllChallenges } \emph{ Delete all challenges }
#' Delete all challenges
#'
#' \itemize{
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteChallenge } \emph{ Delete a challenge }
#' Deletes the challenge specified
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteChallengeOrganizer } \emph{ Delete a challenge organizer }
#' Deletes the challenge organizer specified
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @param } organizer.id character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetChallenge } \emph{ Get a challenge }
#' Returns the challenge specified
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @returnType } \link{Challenge} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Challenge 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetChallengeReadme } \emph{ Get a challenge README }
#' Returns the challenge README specified
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @returnType } \link{ChallengeReadme} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ChallengeReadme 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListAccountChallenges } \emph{ List all the challenges owned by the specified account }
#' List all the challenges owned by the specified account
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfChallenges} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfChallenges 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListChallengeOrganizers } \emph{ List organizers }
#' Lists the organizers of the challenge.
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @returnType } \link{ChallengeOrganizerList} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ChallengeOrganizerList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListChallengeStargazers } \emph{ List stargazers }
#' Lists the people that have starred the challenge.
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfUsers} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfUsers 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListChallengeTopics } \emph{ List stargazers }
#' Lists the challenge topics.
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @returnType } \link{ArrayOfTopics} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ArrayOfTopics 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListChallenges } \emph{ List all the challenges }
#' Returns all the challenges
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @param } sort Enum < [createdAt, updatedAt] > 
#' \item \emph{ @param } direction Enum < [asc, desc] > 
#' \item \emph{ @param } search.terms character
#' \item \emph{ @param } topics list( character )
#' \item \emph{ @param } status list( \link{ChallengeStatus} )
#' \item \emph{ @param } platform.ids list( character )
#' \item \emph{ @param } start.date.range \link{DateRange}
#' \item \emph{ @returnType } \link{PageOfChallenges} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfChallenges 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateChallengeReadme } \emph{ Update a challenge README }
#' Update a challenge README
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#' \item \emph{ @param } challenge.readme.update.request \link{ChallengeReadmeUpdateRequest}
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.create.request <- ChallengeCreateRequest$new() # ChallengeCreateRequest | 
#'
#' #Add a challenge
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$CreateChallenge(var.account.name, var.challenge.create.request)
#'
#'
#' ####################  CreateChallengeOrganizer  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#' var.challenge.organizer.create.request <- ChallengeOrganizerCreateRequest$new() # ChallengeOrganizerCreateRequest | 
#'
#' #Create a challenge organizer
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$CreateChallengeOrganizer(var.account.name, var.challenge.name, var.challenge.organizer.create.request)
#'
#'
#' ####################  DeleteAllChallenges  ####################
#'
#' library(openapi)
#'
#' #Delete all challenges
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$DeleteAllChallenges()
#'
#'
#' ####################  DeleteChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Delete a challenge
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$DeleteChallenge(var.account.name, var.challenge.name)
#'
#'
#' ####################  DeleteChallengeOrganizer  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#' var.organizer.id <- 'organizer.id_example' # character | The identifier of the challenge organizer
#'
#' #Delete a challenge organizer
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$DeleteChallengeOrganizer(var.account.name, var.challenge.name, var.organizer.id)
#'
#'
#' ####################  GetChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Get a challenge
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$GetChallenge(var.account.name, var.challenge.name)
#'
#'
#' ####################  GetChallengeReadme  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Get a challenge README
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$GetChallengeReadme(var.account.name, var.challenge.name)
#'
#'
#' ####################  ListAccountChallenges  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List all the challenges owned by the specified account
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$ListAccountChallenges(var.account.name, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListChallengeOrganizers  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #List organizers
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$ListChallengeOrganizers(var.account.name, var.challenge.name)
#'
#'
#' ####################  ListChallengeStargazers  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List stargazers
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$ListChallengeStargazers(var.account.name, var.challenge.name, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListChallengeTopics  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #List stargazers
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$ListChallengeTopics(var.account.name, var.challenge.name)
#'
#'
#' ####################  ListChallenges  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#' var.sort <- 'sort_example' # character | Property used to sort the results that must be returned
#' var.direction <- 'direction_example' # character | Can be either `asc` or `desc`. Ignored without `sort` parameter.
#' var.search.terms <- 'search.terms_example' # character | A string of search terms used to filter the results
#' var.topics <- ['topics_example'] # array[character] | Array of topics used to filter the results
#' var.status <- [ChallengeStatus$new()] # array[ChallengeStatus] | Array of challenge status used to filter the results
#' var.platform.ids <- ['platform.ids_example'] # array[character] | Array of challenge platform ids used to filter the results
#' var.start.date.range <- DateRange$new() # DateRange | Return challenges that start during the date range specified
#'
#' #List all the challenges
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$ListChallenges(limit=var.limit, offset=var.offset, sort=var.sort, direction=var.direction, search.terms=var.search.terms, topics=var.topics, status=var.status, platform.ids=var.platform.ids, start.date.range=var.start.date.range)
#'
#'
#' ####################  UpdateChallengeReadme  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#' var.challenge.readme.update.request <- ChallengeReadmeUpdateRequest$new() # ChallengeReadmeUpdateRequest | 
#'
#' #Update a challenge README
#' api.instance <- ChallengeApi$new()
#'
#' result <- api.instance$UpdateChallengeReadme(var.account.name, var.challenge.name, var.challenge.readme.update.request)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ChallengeApi <- R6::R6Class(
  'ChallengeApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CreateChallenge = function(account.name, challenge.create.request, ...){
      apiResponse <- self$CreateChallengeWithHttpInfo(account.name, challenge.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateChallengeWithHttpInfo = function(account.name, challenge.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.create.request`)) {
        stop("Missing required parameter `challenge.create.request`.")
      }

      if (!missing(`challenge.create.request`)) {
        body <- `challenge.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/challenges/{accountName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ChallengeCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    CreateChallengeOrganizer = function(account.name, challenge.name, challenge.organizer.create.request, ...){
      apiResponse <- self$CreateChallengeOrganizerWithHttpInfo(account.name, challenge.name, challenge.organizer.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateChallengeOrganizerWithHttpInfo = function(account.name, challenge.name, challenge.organizer.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      if (missing(`challenge.organizer.create.request`)) {
        stop("Missing required parameter `challenge.organizer.create.request`.")
      }

      if (!missing(`challenge.organizer.create.request`)) {
        body <- `challenge.organizer.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/challenges/{accountName}/{challengeName}/organizers"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ChallengeOrganizerCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteAllChallenges = function(...){
      apiResponse <- self$DeleteAllChallengesWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteAllChallengesWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/challenges"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteChallenge = function(account.name, challenge.name, ...){
      apiResponse <- self$DeleteChallengeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteChallengeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteChallengeOrganizer = function(account.name, challenge.name, organizer.id, ...){
      apiResponse <- self$DeleteChallengeOrganizerWithHttpInfo(account.name, challenge.name, organizer.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteChallengeOrganizerWithHttpInfo = function(account.name, challenge.name, organizer.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      if (missing(`organizer.id`)) {
        stop("Missing required parameter `organizer.id`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}/organizers/{organizerId}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`organizer.id`)) {
        urlPath <- gsub(paste0("\\{", "organizerId", "\\}"), URLencode(as.character(`organizer.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetChallenge = function(account.name, challenge.name, ...){
      apiResponse <- self$GetChallengeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetChallengeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Challenge", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetChallengeReadme = function(account.name, challenge.name, ...){
      apiResponse <- self$GetChallengeReadmeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetChallengeReadmeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}/readme"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ChallengeReadme", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListAccountChallenges = function(account.name, limit=10, offset=0, ...){
      apiResponse <- self$ListAccountChallengesWithHttpInfo(account.name, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListAccountChallengesWithHttpInfo = function(account.name, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/challenges/{accountName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfChallenges", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListChallengeOrganizers = function(account.name, challenge.name, ...){
      apiResponse <- self$ListChallengeOrganizersWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListChallengeOrganizersWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}/organizers"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ChallengeOrganizerList", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListChallengeStargazers = function(account.name, challenge.name, limit=10, offset=0, ...){
      apiResponse <- self$ListChallengeStargazersWithHttpInfo(account.name, challenge.name, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListChallengeStargazersWithHttpInfo = function(account.name, challenge.name, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}/stargazers"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfUsers", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListChallengeTopics = function(account.name, challenge.name, ...){
      apiResponse <- self$ListChallengeTopicsWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListChallengeTopicsWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/challenges/{accountName}/{challengeName}/topics"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ArrayOfTopics", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListChallenges = function(limit=10, offset=0, sort=NULL, direction=NULL, search.terms=NULL, topics=NULL, status=NULL, platform.ids=NULL, start.date.range=NULL, ...){
      apiResponse <- self$ListChallengesWithHttpInfo(limit, offset, sort, direction, search.terms, topics, status, platform.ids, start.date.range, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListChallengesWithHttpInfo = function(limit=10, offset=0, sort=NULL, direction=NULL, search.terms=NULL, topics=NULL, status=NULL, platform.ids=NULL, start.date.range=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      queryParams['sort'] <- sort

      queryParams['direction'] <- direction

      queryParams['searchTerms'] <- search.terms

      queryParams['topics'] <- topics

      queryParams['status'] <- status

      queryParams['platformIds'] <- platform.ids

      queryParams['startDateRange'] <- start.date.range

      body <- NULL
      urlPath <- "/challenges"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfChallenges", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UpdateChallengeReadme = function(account.name, challenge.name, challenge.readme.update.request, ...){
      apiResponse <- self$UpdateChallengeReadmeWithHttpInfo(account.name, challenge.name, challenge.readme.update.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UpdateChallengeReadmeWithHttpInfo = function(account.name, challenge.name, challenge.readme.update.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      if (missing(`challenge.readme.update.request`)) {
        stop("Missing required parameter `challenge.readme.update.request`.")
      }

      if (!missing(`challenge.readme.update.request`)) {
        body <- `challenge.readme.update.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/challenges/{accountName}/{challengeName}/readme"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PATCH",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
