# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeAllOf
#'
#' @description ChallengeAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field fullName  character 
#'
#' @field ownerId  character 
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeAllOf <- R6::R6Class(
  'ChallengeAllOf',
  public = list(
    `fullName` = NULL,
    `ownerId` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    initialize = function(
        `fullName`, `ownerId`, `createdAt`, `updatedAt`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`fullName`)) {
        stopifnot(is.character(`fullName`), length(`fullName`) == 1)
        self$`fullName` <- `fullName`
      }
      if (!missing(`ownerId`)) {
        stopifnot(is.character(`ownerId`), length(`ownerId`) == 1)
        self$`ownerId` <- `ownerId`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
    },
    toJSON = function() {
      ChallengeAllOfObject <- list()
      if (!is.null(self$`fullName`)) {
        ChallengeAllOfObject[['fullName']] <-
          self$`fullName`
      }
      if (!is.null(self$`ownerId`)) {
        ChallengeAllOfObject[['ownerId']] <-
          self$`ownerId`
      }
      if (!is.null(self$`createdAt`)) {
        ChallengeAllOfObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        ChallengeAllOfObject[['updatedAt']] <-
          self$`updatedAt`
      }

      ChallengeAllOfObject
    },
    fromJSON = function(ChallengeAllOfJson) {
      ChallengeAllOfObject <- jsonlite::fromJSON(ChallengeAllOfJson)
      if (!is.null(ChallengeAllOfObject$`fullName`)) {
        self$`fullName` <- ChallengeAllOfObject$`fullName`
      }
      if (!is.null(ChallengeAllOfObject$`ownerId`)) {
        self$`ownerId` <- ChallengeAllOfObject$`ownerId`
      }
      if (!is.null(ChallengeAllOfObject$`createdAt`)) {
        self$`createdAt` <- ChallengeAllOfObject$`createdAt`
      }
      if (!is.null(ChallengeAllOfObject$`updatedAt`)) {
        self$`updatedAt` <- ChallengeAllOfObject$`updatedAt`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`fullName`)) {
        sprintf(
        '"fullName":
          "%s"
                ',
        self$`fullName`
        )},
        if (!is.null(self$`ownerId`)) {
        sprintf(
        '"ownerId":
          "%s"
                ',
        self$`ownerId`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeAllOfJson) {
      ChallengeAllOfObject <- jsonlite::fromJSON(ChallengeAllOfJson)
      self$`fullName` <- ChallengeAllOfObject$`fullName`
      self$`ownerId` <- ChallengeAllOfObject$`ownerId`
      self$`createdAt` <- ChallengeAllOfObject$`createdAt`
      self$`updatedAt` <- ChallengeAllOfObject$`updatedAt`
      self
    }
  )
)
