# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeOrganizer
#'
#' @description ChallengeOrganizer Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field name  character 
#'
#' @field login  character [optional]
#'
#' @field roles  list( \link{ChallengeOrganizerRole} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeOrganizer <- R6::R6Class(
  'ChallengeOrganizer',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `login` = NULL,
    `roles` = NULL,
    initialize = function(
        `id`, `name`, `login`=NULL, `roles`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!is.null(`roles`)) {
        stopifnot(is.vector(`roles`), length(`roles`) != 0)
        sapply(`roles`, function(x) stopifnot(R6::is.R6(x)))
        self$`roles` <- `roles`
      }
    },
    toJSON = function() {
      ChallengeOrganizerObject <- list()
      if (!is.null(self$`id`)) {
        ChallengeOrganizerObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ChallengeOrganizerObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`login`)) {
        ChallengeOrganizerObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`roles`)) {
        ChallengeOrganizerObject[['roles']] <-
          lapply(self$`roles`, function(x) x$toJSON())
      }

      ChallengeOrganizerObject
    },
    fromJSON = function(ChallengeOrganizerJson) {
      ChallengeOrganizerObject <- jsonlite::fromJSON(ChallengeOrganizerJson)
      if (!is.null(ChallengeOrganizerObject$`id`)) {
        self$`id` <- ChallengeOrganizerObject$`id`
      }
      if (!is.null(ChallengeOrganizerObject$`name`)) {
        self$`name` <- ChallengeOrganizerObject$`name`
      }
      if (!is.null(ChallengeOrganizerObject$`login`)) {
        self$`login` <- ChallengeOrganizerObject$`login`
      }
      if (!is.null(ChallengeOrganizerObject$`roles`)) {
        self$`roles` <- ApiClient$new()$deserializeObj(ChallengeOrganizerObject$`roles`, "array[ChallengeOrganizerRole]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`roles`)) {
        sprintf(
        '"roles":
        [%s]
',
        paste(sapply(self$`roles`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeOrganizerJson) {
      ChallengeOrganizerObject <- jsonlite::fromJSON(ChallengeOrganizerJson)
      self$`id` <- ChallengeOrganizerObject$`id`
      self$`name` <- ChallengeOrganizerObject$`name`
      self$`login` <- ChallengeOrganizerObject$`login`
      self$`roles` <- ApiClient$new()$deserializeObj(ChallengeOrganizerObject$`roles`, "array[ChallengeOrganizerRole]", loadNamespace("openapi"))
      self
    }
  )
)
