# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeOrganizerRole
#'
#' @description ChallengeOrganizerRole Class
#'
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeOrganizerRole <- R6::R6Class(
    "ChallengeOrganizerRole",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)
            enumvec <- .parse_ChallengeOrganizerRole()

            stopifnot(length(val) == 1L)

            if (!val %in% enumvec)
                stop("Use one of the valid values: ",
                    paste0(enumvec, collapse = ", "))
            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(ChallengeOrganizerRoleJson) {
            private$value <- jsonlite::fromJSON(ChallengeOrganizerRoleJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(ChallengeOrganizerRoleJson) {
            private$value <- jsonlite::fromJSON(ChallengeOrganizerRoleJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_ChallengeOrganizerRole <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[ChallengeLead, InfrastructureLead]"
    )
    unlist(strsplit(res, ", "))
}

