# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeReadme
#'
#' @description ChallengeReadme Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field text  character 
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeReadme <- R6::R6Class(
  'ChallengeReadme',
  public = list(
    `id` = NULL,
    `text` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    initialize = function(
        `id`, `text`, `createdAt`, `updatedAt`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`text`)) {
        stopifnot(is.character(`text`), length(`text`) == 1)
        self$`text` <- `text`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
    },
    toJSON = function() {
      ChallengeReadmeObject <- list()
      if (!is.null(self$`id`)) {
        ChallengeReadmeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`text`)) {
        ChallengeReadmeObject[['text']] <-
          self$`text`
      }
      if (!is.null(self$`createdAt`)) {
        ChallengeReadmeObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        ChallengeReadmeObject[['updatedAt']] <-
          self$`updatedAt`
      }

      ChallengeReadmeObject
    },
    fromJSON = function(ChallengeReadmeJson) {
      ChallengeReadmeObject <- jsonlite::fromJSON(ChallengeReadmeJson)
      if (!is.null(ChallengeReadmeObject$`id`)) {
        self$`id` <- ChallengeReadmeObject$`id`
      }
      if (!is.null(ChallengeReadmeObject$`text`)) {
        self$`text` <- ChallengeReadmeObject$`text`
      }
      if (!is.null(ChallengeReadmeObject$`createdAt`)) {
        self$`createdAt` <- ChallengeReadmeObject$`createdAt`
      }
      if (!is.null(ChallengeReadmeObject$`updatedAt`)) {
        self$`updatedAt` <- ChallengeReadmeObject$`updatedAt`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`text`)) {
        sprintf(
        '"text":
          "%s"
                ',
        self$`text`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeReadmeJson) {
      ChallengeReadmeObject <- jsonlite::fromJSON(ChallengeReadmeJson)
      self$`id` <- ChallengeReadmeObject$`id`
      self$`text` <- ChallengeReadmeObject$`text`
      self$`createdAt` <- ChallengeReadmeObject$`createdAt`
      self$`updatedAt` <- ChallengeReadmeObject$`updatedAt`
      self
    }
  )
)
