# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengeOrganizerList
#'
#' @description ChallengeOrganizerList Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field challengeOrganizers  list( \link{ChallengeOrganizer} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengeOrganizerList <- R6::R6Class(
  'ChallengeOrganizerList',
  public = list(
    `challengeOrganizers` = NULL,
    initialize = function(
        `challengeOrganizers`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`challengeOrganizers`)) {
        stopifnot(is.vector(`challengeOrganizers`), length(`challengeOrganizers`) != 0)
        sapply(`challengeOrganizers`, function(x) stopifnot(R6::is.R6(x)))
        self$`challengeOrganizers` <- `challengeOrganizers`
      }
    },
    toJSON = function() {
      ChallengeOrganizerListObject <- list()
      if (!is.null(self$`challengeOrganizers`)) {
        ChallengeOrganizerListObject[['challengeOrganizers']] <-
          lapply(self$`challengeOrganizers`, function(x) x$toJSON())
      }

      ChallengeOrganizerListObject
    },
    fromJSON = function(ChallengeOrganizerListJson) {
      ChallengeOrganizerListObject <- jsonlite::fromJSON(ChallengeOrganizerListJson)
      if (!is.null(ChallengeOrganizerListObject$`challengeOrganizers`)) {
        self$`challengeOrganizers` <- ApiClient$new()$deserializeObj(ChallengeOrganizerListObject$`challengeOrganizers`, "array[ChallengeOrganizer]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`challengeOrganizers`)) {
        sprintf(
        '"challengeOrganizers":
        [%s]
',
        paste(sapply(self$`challengeOrganizers`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeOrganizerListJson) {
      ChallengeOrganizerListObject <- jsonlite::fromJSON(ChallengeOrganizerListJson)
      self$`challengeOrganizers` <- ApiClient$new()$deserializeObj(ChallengeOrganizerListObject$`challengeOrganizers`, "array[ChallengeOrganizer]", loadNamespace("openapi"))
      self
    }
  )
)
