# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ChallengePlatform
#'
#' @description ChallengePlatform Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field name  character 
#'
#' @field displayName  character 
#'
#' @field websiteUrl  character 
#'
#' @field avatarUrl  character 
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ChallengePlatform <- R6::R6Class(
  'ChallengePlatform',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `displayName` = NULL,
    `websiteUrl` = NULL,
    `avatarUrl` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    initialize = function(
        `id`, `name`, `displayName`, `websiteUrl`, `avatarUrl`, `createdAt`, `updatedAt`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`displayName`)) {
        stopifnot(is.character(`displayName`), length(`displayName`) == 1)
        self$`displayName` <- `displayName`
      }
      if (!missing(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!missing(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
    },
    toJSON = function() {
      ChallengePlatformObject <- list()
      if (!is.null(self$`id`)) {
        ChallengePlatformObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ChallengePlatformObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`displayName`)) {
        ChallengePlatformObject[['displayName']] <-
          self$`displayName`
      }
      if (!is.null(self$`websiteUrl`)) {
        ChallengePlatformObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`avatarUrl`)) {
        ChallengePlatformObject[['avatarUrl']] <-
          self$`avatarUrl`
      }
      if (!is.null(self$`createdAt`)) {
        ChallengePlatformObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        ChallengePlatformObject[['updatedAt']] <-
          self$`updatedAt`
      }

      ChallengePlatformObject
    },
    fromJSON = function(ChallengePlatformJson) {
      ChallengePlatformObject <- jsonlite::fromJSON(ChallengePlatformJson)
      if (!is.null(ChallengePlatformObject$`id`)) {
        self$`id` <- ChallengePlatformObject$`id`
      }
      if (!is.null(ChallengePlatformObject$`name`)) {
        self$`name` <- ChallengePlatformObject$`name`
      }
      if (!is.null(ChallengePlatformObject$`displayName`)) {
        self$`displayName` <- ChallengePlatformObject$`displayName`
      }
      if (!is.null(ChallengePlatformObject$`websiteUrl`)) {
        self$`websiteUrl` <- ChallengePlatformObject$`websiteUrl`
      }
      if (!is.null(ChallengePlatformObject$`avatarUrl`)) {
        self$`avatarUrl` <- ChallengePlatformObject$`avatarUrl`
      }
      if (!is.null(ChallengePlatformObject$`createdAt`)) {
        self$`createdAt` <- ChallengePlatformObject$`createdAt`
      }
      if (!is.null(ChallengePlatformObject$`updatedAt`)) {
        self$`updatedAt` <- ChallengePlatformObject$`updatedAt`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`displayName`)) {
        sprintf(
        '"displayName":
          "%s"
                ',
        self$`displayName`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengePlatformJson) {
      ChallengePlatformObject <- jsonlite::fromJSON(ChallengePlatformJson)
      self$`id` <- ChallengePlatformObject$`id`
      self$`name` <- ChallengePlatformObject$`name`
      self$`displayName` <- ChallengePlatformObject$`displayName`
      self$`websiteUrl` <- ChallengePlatformObject$`websiteUrl`
      self$`avatarUrl` <- ChallengePlatformObject$`avatarUrl`
      self$`createdAt` <- ChallengePlatformObject$`createdAt`
      self$`updatedAt` <- ChallengePlatformObject$`updatedAt`
      self
    }
  )
)
