# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DateRange
#'
#' @description DateRange Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field start  character [optional]
#'
#' @field end  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DateRange <- R6::R6Class(
  'DateRange',
  public = list(
    `start` = NULL,
    `end` = NULL,
    initialize = function(
        `start`=NULL, `end`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`start`)) {
        stopifnot(is.character(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!is.null(`end`)) {
        stopifnot(is.character(`end`), length(`end`) == 1)
        self$`end` <- `end`
      }
    },
    toJSON = function() {
      DateRangeObject <- list()
      if (!is.null(self$`start`)) {
        DateRangeObject[['start']] <-
          self$`start`
      }
      if (!is.null(self$`end`)) {
        DateRangeObject[['end']] <-
          self$`end`
      }

      DateRangeObject
    },
    fromJSON = function(DateRangeJson) {
      DateRangeObject <- jsonlite::fromJSON(DateRangeJson)
      if (!is.null(DateRangeObject$`start`)) {
        self$`start` <- DateRangeObject$`start`
      }
      if (!is.null(DateRangeObject$`end`)) {
        self$`end` <- DateRangeObject$`end`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`start`)) {
        sprintf(
        '"start":
          "%s"
                ',
        self$`start`
        )},
        if (!is.null(self$`end`)) {
        sprintf(
        '"end":
          "%s"
                ',
        self$`end`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DateRangeJson) {
      DateRangeObject <- jsonlite::fromJSON(DateRangeJson)
      self$`start` <- DateRangeObject$`start`
      self$`end` <- DateRangeObject$`end`
      self
    }
  )
)
