# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Error
#'
#' @description Error Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field title  character 
#'
#' @field status  integer 
#'
#' @field detail  character [optional]
#'
#' @field type  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Error <- R6::R6Class(
  'Error',
  public = list(
    `title` = NULL,
    `status` = NULL,
    `detail` = NULL,
    `type` = NULL,
    initialize = function(
        `title`, `status`, `detail`=NULL, `type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`status`)) {
        stopifnot(is.numeric(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`detail`)) {
        stopifnot(is.character(`detail`), length(`detail`) == 1)
        self$`detail` <- `detail`
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      ErrorObject <- list()
      if (!is.null(self$`title`)) {
        ErrorObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`status`)) {
        ErrorObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`detail`)) {
        ErrorObject[['detail']] <-
          self$`detail`
      }
      if (!is.null(self$`type`)) {
        ErrorObject[['type']] <-
          self$`type`
      }

      ErrorObject
    },
    fromJSON = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      if (!is.null(ErrorObject$`title`)) {
        self$`title` <- ErrorObject$`title`
      }
      if (!is.null(ErrorObject$`status`)) {
        self$`status` <- ErrorObject$`status`
      }
      if (!is.null(ErrorObject$`detail`)) {
        self$`detail` <- ErrorObject$`detail`
      }
      if (!is.null(ErrorObject$`type`)) {
        self$`type` <- ErrorObject$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          %d
                ',
        self$`status`
        )},
        if (!is.null(self$`detail`)) {
        sprintf(
        '"detail":
          "%s"
                ',
        self$`detail`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      self$`title` <- ErrorObject$`title`
      self$`status` <- ErrorObject$`status`
      self$`detail` <- ErrorObject$`detail`
      self$`type` <- ErrorObject$`type`
      self
    }
  )
)
