# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Grant operations
#' @description openapi.Grant
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateGrant } \emph{ Create a grant }
#' Create a grant with the specified name
#'
#' \itemize{
#' \item \emph{ @param } grant.create.request \link{GrantCreateRequest}
#' \item \emph{ @returnType } \link{GrantCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : GrantCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteAllGrants } \emph{ Delete all grants }
#' Delete all grants
#'
#' \itemize{
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteGrant } \emph{ Delete a grant }
#' Deletes the grant specified
#'
#' \itemize{
#' \item \emph{ @param } grant.id character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetGrant } \emph{ Get a grant }
#' Returns the grant specified
#'
#' \itemize{
#' \item \emph{ @param } grant.id character
#' \item \emph{ @returnType } \link{Grant} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Grant 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListGrants } \emph{ Get all grants }
#' Returns the grants
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfGrants} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfGrants 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateGrant  ####################
#'
#' library(openapi)
#' var.grant.create.request <- GrantCreateRequest$new() # GrantCreateRequest | 
#'
#' #Create a grant
#' api.instance <- GrantApi$new()
#'
#' result <- api.instance$CreateGrant(var.grant.create.request)
#'
#'
#' ####################  DeleteAllGrants  ####################
#'
#' library(openapi)
#'
#' #Delete all grants
#' api.instance <- GrantApi$new()
#'
#' result <- api.instance$DeleteAllGrants()
#'
#'
#' ####################  DeleteGrant  ####################
#'
#' library(openapi)
#' var.grant.id <- 'grant.id_example' # character | The ID of the grant that is being created
#'
#' #Delete a grant
#' api.instance <- GrantApi$new()
#'
#' result <- api.instance$DeleteGrant(var.grant.id)
#'
#'
#' ####################  GetGrant  ####################
#'
#' library(openapi)
#' var.grant.id <- 'grant.id_example' # character | The ID of the grant that is being created
#'
#' #Get a grant
#' api.instance <- GrantApi$new()
#'
#' result <- api.instance$GetGrant(var.grant.id)
#'
#'
#' ####################  ListGrants  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #Get all grants
#' api.instance <- GrantApi$new()
#'
#' result <- api.instance$ListGrants(limit=var.limit, offset=var.offset)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
GrantApi <- R6::R6Class(
  'GrantApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CreateGrant = function(grant.create.request, ...){
      apiResponse <- self$CreateGrantWithHttpInfo(grant.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateGrantWithHttpInfo = function(grant.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`grant.create.request`)) {
        stop("Missing required parameter `grant.create.request`.")
      }

      if (!missing(`grant.create.request`)) {
        body <- `grant.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/grants"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "GrantCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteAllGrants = function(...){
      apiResponse <- self$DeleteAllGrantsWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteAllGrantsWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/grants"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteGrant = function(grant.id, ...){
      apiResponse <- self$DeleteGrantWithHttpInfo(grant.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteGrantWithHttpInfo = function(grant.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`grant.id`)) {
        stop("Missing required parameter `grant.id`.")
      }

      body <- NULL
      urlPath <- "/grants/{grantId}"
      if (!missing(`grant.id`)) {
        urlPath <- gsub(paste0("\\{", "grantId", "\\}"), URLencode(as.character(`grant.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetGrant = function(grant.id, ...){
      apiResponse <- self$GetGrantWithHttpInfo(grant.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetGrantWithHttpInfo = function(grant.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`grant.id`)) {
        stop("Missing required parameter `grant.id`.")
      }

      body <- NULL
      urlPath <- "/grants/{grantId}"
      if (!missing(`grant.id`)) {
        urlPath <- gsub(paste0("\\{", "grantId", "\\}"), URLencode(as.character(`grant.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Grant", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListGrants = function(limit=10, offset=0, ...){
      apiResponse <- self$ListGrantsWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListGrantsWithHttpInfo = function(limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/grants"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfGrants", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
