# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title HealthCheck
#'
#' @description HealthCheck Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field status  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HealthCheck <- R6::R6Class(
  'HealthCheck',
  public = list(
    `status` = NULL,
    initialize = function(
        `status`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      HealthCheckObject <- list()
      if (!is.null(self$`status`)) {
        HealthCheckObject[['status']] <-
          self$`status`
      }

      HealthCheckObject
    },
    fromJSON = function(HealthCheckJson) {
      HealthCheckObject <- jsonlite::fromJSON(HealthCheckJson)
      if (!is.null(HealthCheckObject$`status`)) {
        self$`status` <- HealthCheckObject$`status`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(HealthCheckJson) {
      HealthCheckObject <- jsonlite::fromJSON(HealthCheckJson)
      self$`status` <- HealthCheckObject$`status`
      self
    }
  )
)
