# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalAuthRequest
#'
#' @description LocalAuthRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field login  character 
#'
#' @field password  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalAuthRequest <- R6::R6Class(
  'LocalAuthRequest',
  public = list(
    `login` = NULL,
    `password` = NULL,
    initialize = function(
        `login`, `password`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
    },
    toJSON = function() {
      LocalAuthRequestObject <- list()
      if (!is.null(self$`login`)) {
        LocalAuthRequestObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`password`)) {
        LocalAuthRequestObject[['password']] <-
          self$`password`
      }

      LocalAuthRequestObject
    },
    fromJSON = function(LocalAuthRequestJson) {
      LocalAuthRequestObject <- jsonlite::fromJSON(LocalAuthRequestJson)
      if (!is.null(LocalAuthRequestObject$`login`)) {
        self$`login` <- LocalAuthRequestObject$`login`
      }
      if (!is.null(LocalAuthRequestObject$`password`)) {
        self$`password` <- LocalAuthRequestObject$`password`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`password`)) {
        sprintf(
        '"password":
          "%s"
                ',
        self$`password`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalAuthRequestJson) {
      LocalAuthRequestObject <- jsonlite::fromJSON(LocalAuthRequestJson)
      self$`login` <- LocalAuthRequestObject$`login`
      self$`password` <- LocalAuthRequestObject$`password`
      self
    }
  )
)
