# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OrgMembership operations
#' @description openapi.OrgMembership
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateOrgMembership } \emph{ Create an org membership }
#' Create an org membership
#'
#' \itemize{
#' \item \emph{ @param } org.membership.create.request \link{OrgMembershipCreateRequest}
#' \item \emph{ @returnType } \link{OrgMembershipCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : OrgMembershipCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteAllOrgMemberships } \emph{ Delete all org memberships }
#' Delete all org memberships
#'
#' \itemize{
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteOrgMembership } \emph{ Delete an org membership }
#' Deletes the org membership specified
#'
#' \itemize{
#' \item \emph{ @param } org.membership.id character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetOrgMembership } \emph{ Get an org membership }
#' Returns the org membership specified
#'
#' \itemize{
#' \item \emph{ @param } org.membership.id character
#' \item \emph{ @returnType } \link{OrgMembership} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : OrgMembership 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListOrgMemberships } \emph{ List all the org memberships }
#' Returns the org memberships
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @param } org.id character
#' \item \emph{ @param } user.id character
#' \item \emph{ @returnType } \link{PageOfOrgMemberships} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfOrgMemberships 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateOrgMembership  ####################
#'
#' library(openapi)
#' var.org.membership.create.request <- OrgMembershipCreateRequest$new() # OrgMembershipCreateRequest | 
#'
#' #Create an org membership
#' api.instance <- OrgMembershipApi$new()
#'
#' result <- api.instance$CreateOrgMembership(var.org.membership.create.request)
#'
#'
#' ####################  DeleteAllOrgMemberships  ####################
#'
#' library(openapi)
#'
#' #Delete all org memberships
#' api.instance <- OrgMembershipApi$new()
#'
#' result <- api.instance$DeleteAllOrgMemberships()
#'
#'
#' ####################  DeleteOrgMembership  ####################
#'
#' library(openapi)
#' var.org.membership.id <- 'org.membership.id_example' # character | The unique identifier of the org membership
#'
#' #Delete an org membership
#' api.instance <- OrgMembershipApi$new()
#'
#' result <- api.instance$DeleteOrgMembership(var.org.membership.id)
#'
#'
#' ####################  GetOrgMembership  ####################
#'
#' library(openapi)
#' var.org.membership.id <- 'org.membership.id_example' # character | The unique identifier of the org membership
#'
#' #Get an org membership
#' api.instance <- OrgMembershipApi$new()
#'
#' result <- api.instance$GetOrgMembership(var.org.membership.id)
#'
#'
#' ####################  ListOrgMemberships  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#' var.org.id <- 'org.id_example' # character | An organization identifier used to filter the results
#' var.user.id <- 'user.id_example' # character | A user identifier used to filter the results
#'
#' #List all the org memberships
#' api.instance <- OrgMembershipApi$new()
#'
#' result <- api.instance$ListOrgMemberships(limit=var.limit, offset=var.offset, org.id=var.org.id, user.id=var.user.id)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
OrgMembershipApi <- R6::R6Class(
  'OrgMembershipApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CreateOrgMembership = function(org.membership.create.request, ...){
      apiResponse <- self$CreateOrgMembershipWithHttpInfo(org.membership.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateOrgMembershipWithHttpInfo = function(org.membership.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`org.membership.create.request`)) {
        stop("Missing required parameter `org.membership.create.request`.")
      }

      if (!missing(`org.membership.create.request`)) {
        body <- `org.membership.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/orgMemberships"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "OrgMembershipCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteAllOrgMemberships = function(...){
      apiResponse <- self$DeleteAllOrgMembershipsWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteAllOrgMembershipsWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/orgMemberships"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteOrgMembership = function(org.membership.id, ...){
      apiResponse <- self$DeleteOrgMembershipWithHttpInfo(org.membership.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteOrgMembershipWithHttpInfo = function(org.membership.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`org.membership.id`)) {
        stop("Missing required parameter `org.membership.id`.")
      }

      body <- NULL
      urlPath <- "/orgMemberships/{orgMembershipId}"
      if (!missing(`org.membership.id`)) {
        urlPath <- gsub(paste0("\\{", "orgMembershipId", "\\}"), URLencode(as.character(`org.membership.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetOrgMembership = function(org.membership.id, ...){
      apiResponse <- self$GetOrgMembershipWithHttpInfo(org.membership.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetOrgMembershipWithHttpInfo = function(org.membership.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`org.membership.id`)) {
        stop("Missing required parameter `org.membership.id`.")
      }

      body <- NULL
      urlPath <- "/orgMemberships/{orgMembershipId}"
      if (!missing(`org.membership.id`)) {
        urlPath <- gsub(paste0("\\{", "orgMembershipId", "\\}"), URLencode(as.character(`org.membership.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "OrgMembership", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListOrgMemberships = function(limit=10, offset=0, org.id=NULL, user.id=NULL, ...){
      apiResponse <- self$ListOrgMembershipsWithHttpInfo(limit, offset, org.id, user.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListOrgMembershipsWithHttpInfo = function(limit=10, offset=0, org.id=NULL, user.id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      queryParams['orgId'] <- org.id

      queryParams['userId'] <- user.id

      body <- NULL
      urlPath <- "/orgMemberships"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfOrgMemberships", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
