# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OrgMembershipCreateRequest
#'
#' @description OrgMembershipCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field state  character 
#'
#' @field role  character 
#'
#' @field organizationId  character 
#'
#' @field userId  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrgMembershipCreateRequest <- R6::R6Class(
  'OrgMembershipCreateRequest',
  public = list(
    `state` = NULL,
    `role` = NULL,
    `organizationId` = NULL,
    `userId` = NULL,
    initialize = function(
        `state`, `role`, `organizationId`, `userId`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
        self$`role` <- `role`
      }
      if (!missing(`organizationId`)) {
        stopifnot(is.character(`organizationId`), length(`organizationId`) == 1)
        self$`organizationId` <- `organizationId`
      }
      if (!missing(`userId`)) {
        stopifnot(is.character(`userId`), length(`userId`) == 1)
        self$`userId` <- `userId`
      }
    },
    toJSON = function() {
      OrgMembershipCreateRequestObject <- list()
      if (!is.null(self$`state`)) {
        OrgMembershipCreateRequestObject[['state']] <-
          self$`state`
      }
      if (!is.null(self$`role`)) {
        OrgMembershipCreateRequestObject[['role']] <-
          self$`role`
      }
      if (!is.null(self$`organizationId`)) {
        OrgMembershipCreateRequestObject[['organizationId']] <-
          self$`organizationId`
      }
      if (!is.null(self$`userId`)) {
        OrgMembershipCreateRequestObject[['userId']] <-
          self$`userId`
      }

      OrgMembershipCreateRequestObject
    },
    fromJSON = function(OrgMembershipCreateRequestJson) {
      OrgMembershipCreateRequestObject <- jsonlite::fromJSON(OrgMembershipCreateRequestJson)
      if (!is.null(OrgMembershipCreateRequestObject$`state`)) {
        self$`state` <- OrgMembershipCreateRequestObject$`state`
      }
      if (!is.null(OrgMembershipCreateRequestObject$`role`)) {
        self$`role` <- OrgMembershipCreateRequestObject$`role`
      }
      if (!is.null(OrgMembershipCreateRequestObject$`organizationId`)) {
        self$`organizationId` <- OrgMembershipCreateRequestObject$`organizationId`
      }
      if (!is.null(OrgMembershipCreateRequestObject$`userId`)) {
        self$`userId` <- OrgMembershipCreateRequestObject$`userId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`state`)) {
        sprintf(
        '"state":
          "%s"
                ',
        self$`state`
        )},
        if (!is.null(self$`role`)) {
        sprintf(
        '"role":
          "%s"
                ',
        self$`role`
        )},
        if (!is.null(self$`organizationId`)) {
        sprintf(
        '"organizationId":
          "%s"
                ',
        self$`organizationId`
        )},
        if (!is.null(self$`userId`)) {
        sprintf(
        '"userId":
          "%s"
                ',
        self$`userId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrgMembershipCreateRequestJson) {
      OrgMembershipCreateRequestObject <- jsonlite::fromJSON(OrgMembershipCreateRequestJson)
      self$`state` <- OrgMembershipCreateRequestObject$`state`
      self$`role` <- OrgMembershipCreateRequestObject$`role`
      self$`organizationId` <- OrgMembershipCreateRequestObject$`organizationId`
      self$`userId` <- OrgMembershipCreateRequestObject$`userId`
      self
    }
  )
)
