# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OrgMembership
#'
#' @description OrgMembership Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field state  character 
#'
#' @field role  character 
#'
#' @field organizationId  character 
#'
#' @field userId  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrgMembership <- R6::R6Class(
  'OrgMembership',
  public = list(
    `id` = NULL,
    `state` = NULL,
    `role` = NULL,
    `organizationId` = NULL,
    `userId` = NULL,
    initialize = function(
        `id`, `state`, `role`, `organizationId`, `userId`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
        self$`role` <- `role`
      }
      if (!missing(`organizationId`)) {
        stopifnot(is.character(`organizationId`), length(`organizationId`) == 1)
        self$`organizationId` <- `organizationId`
      }
      if (!missing(`userId`)) {
        stopifnot(is.character(`userId`), length(`userId`) == 1)
        self$`userId` <- `userId`
      }
    },
    toJSON = function() {
      OrgMembershipObject <- list()
      if (!is.null(self$`id`)) {
        OrgMembershipObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`state`)) {
        OrgMembershipObject[['state']] <-
          self$`state`
      }
      if (!is.null(self$`role`)) {
        OrgMembershipObject[['role']] <-
          self$`role`
      }
      if (!is.null(self$`organizationId`)) {
        OrgMembershipObject[['organizationId']] <-
          self$`organizationId`
      }
      if (!is.null(self$`userId`)) {
        OrgMembershipObject[['userId']] <-
          self$`userId`
      }

      OrgMembershipObject
    },
    fromJSON = function(OrgMembershipJson) {
      OrgMembershipObject <- jsonlite::fromJSON(OrgMembershipJson)
      if (!is.null(OrgMembershipObject$`id`)) {
        self$`id` <- OrgMembershipObject$`id`
      }
      if (!is.null(OrgMembershipObject$`state`)) {
        self$`state` <- OrgMembershipObject$`state`
      }
      if (!is.null(OrgMembershipObject$`role`)) {
        self$`role` <- OrgMembershipObject$`role`
      }
      if (!is.null(OrgMembershipObject$`organizationId`)) {
        self$`organizationId` <- OrgMembershipObject$`organizationId`
      }
      if (!is.null(OrgMembershipObject$`userId`)) {
        self$`userId` <- OrgMembershipObject$`userId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`state`)) {
        sprintf(
        '"state":
          "%s"
                ',
        self$`state`
        )},
        if (!is.null(self$`role`)) {
        sprintf(
        '"role":
          "%s"
                ',
        self$`role`
        )},
        if (!is.null(self$`organizationId`)) {
        sprintf(
        '"organizationId":
          "%s"
                ',
        self$`organizationId`
        )},
        if (!is.null(self$`userId`)) {
        sprintf(
        '"userId":
          "%s"
                ',
        self$`userId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrgMembershipJson) {
      OrgMembershipObject <- jsonlite::fromJSON(OrgMembershipJson)
      self$`id` <- OrgMembershipObject$`id`
      self$`state` <- OrgMembershipObject$`state`
      self$`role` <- OrgMembershipObject$`role`
      self$`organizationId` <- OrgMembershipObject$`organizationId`
      self$`userId` <- OrgMembershipObject$`userId`
      self
    }
  )
)
