# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OrganizationCreateRequest
#'
#' @description OrganizationCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field login  character 
#'
#' @field email  character 
#'
#' @field name  character [optional]
#'
#' @field avatarUrl  character [optional]
#'
#' @field websiteUrl  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrganizationCreateRequest <- R6::R6Class(
  'OrganizationCreateRequest',
  public = list(
    `login` = NULL,
    `email` = NULL,
    `name` = NULL,
    `avatarUrl` = NULL,
    `websiteUrl` = NULL,
    `description` = NULL,
    initialize = function(
        `login`, `email`, `name`=NULL, `avatarUrl`=NULL, `websiteUrl`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
      if (!is.null(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      OrganizationCreateRequestObject <- list()
      if (!is.null(self$`login`)) {
        OrganizationCreateRequestObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`email`)) {
        OrganizationCreateRequestObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`name`)) {
        OrganizationCreateRequestObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`avatarUrl`)) {
        OrganizationCreateRequestObject[['avatarUrl']] <-
          self$`avatarUrl`
      }
      if (!is.null(self$`websiteUrl`)) {
        OrganizationCreateRequestObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`description`)) {
        OrganizationCreateRequestObject[['description']] <-
          self$`description`
      }

      OrganizationCreateRequestObject
    },
    fromJSON = function(OrganizationCreateRequestJson) {
      OrganizationCreateRequestObject <- jsonlite::fromJSON(OrganizationCreateRequestJson)
      if (!is.null(OrganizationCreateRequestObject$`login`)) {
        self$`login` <- OrganizationCreateRequestObject$`login`
      }
      if (!is.null(OrganizationCreateRequestObject$`email`)) {
        self$`email` <- OrganizationCreateRequestObject$`email`
      }
      if (!is.null(OrganizationCreateRequestObject$`name`)) {
        self$`name` <- OrganizationCreateRequestObject$`name`
      }
      if (!is.null(OrganizationCreateRequestObject$`avatarUrl`)) {
        self$`avatarUrl` <- OrganizationCreateRequestObject$`avatarUrl`
      }
      if (!is.null(OrganizationCreateRequestObject$`websiteUrl`)) {
        self$`websiteUrl` <- OrganizationCreateRequestObject$`websiteUrl`
      }
      if (!is.null(OrganizationCreateRequestObject$`description`)) {
        self$`description` <- OrganizationCreateRequestObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrganizationCreateRequestJson) {
      OrganizationCreateRequestObject <- jsonlite::fromJSON(OrganizationCreateRequestJson)
      self$`login` <- OrganizationCreateRequestObject$`login`
      self$`email` <- OrganizationCreateRequestObject$`email`
      self$`name` <- OrganizationCreateRequestObject$`name`
      self$`avatarUrl` <- OrganizationCreateRequestObject$`avatarUrl`
      self$`websiteUrl` <- OrganizationCreateRequestObject$`websiteUrl`
      self$`description` <- OrganizationCreateRequestObject$`description`
      self
    }
  )
)
