# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OrganizationAllOf
#'
#' @description OrganizationAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @field type  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrganizationAllOf <- R6::R6Class(
  'OrganizationAllOf',
  public = list(
    `createdAt` = NULL,
    `updatedAt` = NULL,
    `type` = NULL,
    initialize = function(
        `createdAt`, `updatedAt`, `type`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      OrganizationAllOfObject <- list()
      if (!is.null(self$`createdAt`)) {
        OrganizationAllOfObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        OrganizationAllOfObject[['updatedAt']] <-
          self$`updatedAt`
      }
      if (!is.null(self$`type`)) {
        OrganizationAllOfObject[['type']] <-
          self$`type`
      }

      OrganizationAllOfObject
    },
    fromJSON = function(OrganizationAllOfJson) {
      OrganizationAllOfObject <- jsonlite::fromJSON(OrganizationAllOfJson)
      if (!is.null(OrganizationAllOfObject$`createdAt`)) {
        self$`createdAt` <- OrganizationAllOfObject$`createdAt`
      }
      if (!is.null(OrganizationAllOfObject$`updatedAt`)) {
        self$`updatedAt` <- OrganizationAllOfObject$`updatedAt`
      }
      if (!is.null(OrganizationAllOfObject$`type`)) {
        self$`type` <- OrganizationAllOfObject$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrganizationAllOfJson) {
      OrganizationAllOfObject <- jsonlite::fromJSON(OrganizationAllOfJson)
      self$`createdAt` <- OrganizationAllOfObject$`createdAt`
      self$`updatedAt` <- OrganizationAllOfObject$`updatedAt`
      self$`type` <- OrganizationAllOfObject$`type`
      self
    }
  )
)
