# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Organization operations
#' @description openapi.Organization
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateOrganization } \emph{ Create an organization }
#' Create an organization with the specified account name
#'
#' \itemize{
#' \item \emph{ @param } organization.create.request \link{OrganizationCreateRequest}
#' \item \emph{ @returnType } \link{OrganizationCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : OrganizationCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteAllOrganizations } \emph{ Delete all organizations }
#' Delete all organizations
#'
#' \itemize{
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteOrganization } \emph{ Delete an organization }
#' Deletes the organization specified
#'
#' \itemize{
#' \item \emph{ @param } organization.id character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetOrganization } \emph{ Get an organization }
#' Returns the organization specified
#'
#' \itemize{
#' \item \emph{ @param } organization.id character
#' \item \emph{ @returnType } \link{Organization} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Organization 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListOrganizations } \emph{ Get all organizations }
#' Returns the organizations
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfOrganizations} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfOrganizations 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateOrganization  ####################
#'
#' library(openapi)
#' var.organization.create.request <- OrganizationCreateRequest$new() # OrganizationCreateRequest | 
#'
#' #Create an organization
#' api.instance <- OrganizationApi$new()
#'
#' result <- api.instance$CreateOrganization(var.organization.create.request)
#'
#'
#' ####################  DeleteAllOrganizations  ####################
#'
#' library(openapi)
#'
#' #Delete all organizations
#' api.instance <- OrganizationApi$new()
#'
#' result <- api.instance$DeleteAllOrganizations()
#'
#'
#' ####################  DeleteOrganization  ####################
#'
#' library(openapi)
#' var.organization.id <- 'organization.id_example' # character | The unique identifier of the organization, either the user ID or account name
#'
#' #Delete an organization
#' api.instance <- OrganizationApi$new()
#'
#' result <- api.instance$DeleteOrganization(var.organization.id)
#'
#'
#' ####################  GetOrganization  ####################
#'
#' library(openapi)
#' var.organization.id <- 'organization.id_example' # character | The unique identifier of the organization, either the user ID or account name
#'
#' #Get an organization
#' api.instance <- OrganizationApi$new()
#'
#' result <- api.instance$GetOrganization(var.organization.id)
#'
#'
#' ####################  ListOrganizations  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #Get all organizations
#' api.instance <- OrganizationApi$new()
#'
#' result <- api.instance$ListOrganizations(limit=var.limit, offset=var.offset)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
OrganizationApi <- R6::R6Class(
  'OrganizationApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CreateOrganization = function(organization.create.request, ...){
      apiResponse <- self$CreateOrganizationWithHttpInfo(organization.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateOrganizationWithHttpInfo = function(organization.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`organization.create.request`)) {
        stop("Missing required parameter `organization.create.request`.")
      }

      if (!missing(`organization.create.request`)) {
        body <- `organization.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/organizations"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "OrganizationCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteAllOrganizations = function(...){
      apiResponse <- self$DeleteAllOrganizationsWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteAllOrganizationsWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/organizations"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteOrganization = function(organization.id, ...){
      apiResponse <- self$DeleteOrganizationWithHttpInfo(organization.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteOrganizationWithHttpInfo = function(organization.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`organization.id`)) {
        stop("Missing required parameter `organization.id`.")
      }

      body <- NULL
      urlPath <- "/organizations/{organizationId}"
      if (!missing(`organization.id`)) {
        urlPath <- gsub(paste0("\\{", "organizationId", "\\}"), URLencode(as.character(`organization.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetOrganization = function(organization.id, ...){
      apiResponse <- self$GetOrganizationWithHttpInfo(organization.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetOrganizationWithHttpInfo = function(organization.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`organization.id`)) {
        stop("Missing required parameter `organization.id`.")
      }

      body <- NULL
      urlPath <- "/organizations/{organizationId}"
      if (!missing(`organization.id`)) {
        urlPath <- gsub(paste0("\\{", "organizationId", "\\}"), URLencode(as.character(`organization.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Organization", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListOrganizations = function(limit=10, offset=0, ...){
      apiResponse <- self$ListOrganizationsWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListOrganizationsWithHttpInfo = function(limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/organizations"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfOrganizations", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
