# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Organization
#'
#' @description Organization Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field login  character 
#'
#' @field email  character 
#'
#' @field name  character [optional]
#'
#' @field avatarUrl  character [optional]
#'
#' @field websiteUrl  character [optional]
#'
#' @field description  character [optional]
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @field type  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Organization <- R6::R6Class(
  'Organization',
  public = list(
    `id` = NULL,
    `login` = NULL,
    `email` = NULL,
    `name` = NULL,
    `avatarUrl` = NULL,
    `websiteUrl` = NULL,
    `description` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    `type` = NULL,
    initialize = function(
        `id`, `login`, `email`, `createdAt`, `updatedAt`, `type`, `name`=NULL, `avatarUrl`=NULL, `websiteUrl`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
      if (!is.null(`websiteUrl`)) {
        stopifnot(is.character(`websiteUrl`), length(`websiteUrl`) == 1)
        self$`websiteUrl` <- `websiteUrl`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      OrganizationObject <- list()
      if (!is.null(self$`id`)) {
        OrganizationObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`login`)) {
        OrganizationObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`email`)) {
        OrganizationObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`name`)) {
        OrganizationObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`avatarUrl`)) {
        OrganizationObject[['avatarUrl']] <-
          self$`avatarUrl`
      }
      if (!is.null(self$`websiteUrl`)) {
        OrganizationObject[['websiteUrl']] <-
          self$`websiteUrl`
      }
      if (!is.null(self$`description`)) {
        OrganizationObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`createdAt`)) {
        OrganizationObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        OrganizationObject[['updatedAt']] <-
          self$`updatedAt`
      }
      if (!is.null(self$`type`)) {
        OrganizationObject[['type']] <-
          self$`type`
      }

      OrganizationObject
    },
    fromJSON = function(OrganizationJson) {
      OrganizationObject <- jsonlite::fromJSON(OrganizationJson)
      if (!is.null(OrganizationObject$`id`)) {
        self$`id` <- OrganizationObject$`id`
      }
      if (!is.null(OrganizationObject$`login`)) {
        self$`login` <- OrganizationObject$`login`
      }
      if (!is.null(OrganizationObject$`email`)) {
        self$`email` <- OrganizationObject$`email`
      }
      if (!is.null(OrganizationObject$`name`)) {
        self$`name` <- OrganizationObject$`name`
      }
      if (!is.null(OrganizationObject$`avatarUrl`)) {
        self$`avatarUrl` <- OrganizationObject$`avatarUrl`
      }
      if (!is.null(OrganizationObject$`websiteUrl`)) {
        self$`websiteUrl` <- OrganizationObject$`websiteUrl`
      }
      if (!is.null(OrganizationObject$`description`)) {
        self$`description` <- OrganizationObject$`description`
      }
      if (!is.null(OrganizationObject$`createdAt`)) {
        self$`createdAt` <- OrganizationObject$`createdAt`
      }
      if (!is.null(OrganizationObject$`updatedAt`)) {
        self$`updatedAt` <- OrganizationObject$`updatedAt`
      }
      if (!is.null(OrganizationObject$`type`)) {
        self$`type` <- OrganizationObject$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )},
        if (!is.null(self$`websiteUrl`)) {
        sprintf(
        '"websiteUrl":
          "%s"
                ',
        self$`websiteUrl`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrganizationJson) {
      OrganizationObject <- jsonlite::fromJSON(OrganizationJson)
      self$`id` <- OrganizationObject$`id`
      self$`login` <- OrganizationObject$`login`
      self$`email` <- OrganizationObject$`email`
      self$`name` <- OrganizationObject$`name`
      self$`avatarUrl` <- OrganizationObject$`avatarUrl`
      self$`websiteUrl` <- OrganizationObject$`websiteUrl`
      self$`description` <- OrganizationObject$`description`
      self$`createdAt` <- OrganizationObject$`createdAt`
      self$`updatedAt` <- OrganizationObject$`updatedAt`
      self$`type` <- OrganizationObject$`type`
      self
    }
  )
)
