# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfChallengePlatformsAllOf
#'
#' @description PageOfChallengePlatformsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field challengePlatforms  list( \link{ChallengePlatform} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfChallengePlatformsAllOf <- R6::R6Class(
  'PageOfChallengePlatformsAllOf',
  public = list(
    `challengePlatforms` = NULL,
    initialize = function(
        `challengePlatforms`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`challengePlatforms`)) {
        stopifnot(is.vector(`challengePlatforms`), length(`challengePlatforms`) != 0)
        sapply(`challengePlatforms`, function(x) stopifnot(R6::is.R6(x)))
        self$`challengePlatforms` <- `challengePlatforms`
      }
    },
    toJSON = function() {
      PageOfChallengePlatformsAllOfObject <- list()
      if (!is.null(self$`challengePlatforms`)) {
        PageOfChallengePlatformsAllOfObject[['challengePlatforms']] <-
          lapply(self$`challengePlatforms`, function(x) x$toJSON())
      }

      PageOfChallengePlatformsAllOfObject
    },
    fromJSON = function(PageOfChallengePlatformsAllOfJson) {
      PageOfChallengePlatformsAllOfObject <- jsonlite::fromJSON(PageOfChallengePlatformsAllOfJson)
      if (!is.null(PageOfChallengePlatformsAllOfObject$`challengePlatforms`)) {
        self$`challengePlatforms` <- ApiClient$new()$deserializeObj(PageOfChallengePlatformsAllOfObject$`challengePlatforms`, "array[ChallengePlatform]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`challengePlatforms`)) {
        sprintf(
        '"challengePlatforms":
        [%s]
',
        paste(sapply(self$`challengePlatforms`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfChallengePlatformsAllOfJson) {
      PageOfChallengePlatformsAllOfObject <- jsonlite::fromJSON(PageOfChallengePlatformsAllOfJson)
      self$`challengePlatforms` <- ApiClient$new()$deserializeObj(PageOfChallengePlatformsAllOfObject$`challengePlatforms`, "array[ChallengePlatform]", loadNamespace("openapi"))
      self
    }
  )
)
