# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfOrganizationsAllOf
#'
#' @description PageOfOrganizationsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field organizations  list( \link{Organization} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfOrganizationsAllOf <- R6::R6Class(
  'PageOfOrganizationsAllOf',
  public = list(
    `organizations` = NULL,
    initialize = function(
        `organizations`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`organizations`)) {
        stopifnot(is.vector(`organizations`), length(`organizations`) != 0)
        sapply(`organizations`, function(x) stopifnot(R6::is.R6(x)))
        self$`organizations` <- `organizations`
      }
    },
    toJSON = function() {
      PageOfOrganizationsAllOfObject <- list()
      if (!is.null(self$`organizations`)) {
        PageOfOrganizationsAllOfObject[['organizations']] <-
          lapply(self$`organizations`, function(x) x$toJSON())
      }

      PageOfOrganizationsAllOfObject
    },
    fromJSON = function(PageOfOrganizationsAllOfJson) {
      PageOfOrganizationsAllOfObject <- jsonlite::fromJSON(PageOfOrganizationsAllOfJson)
      if (!is.null(PageOfOrganizationsAllOfObject$`organizations`)) {
        self$`organizations` <- ApiClient$new()$deserializeObj(PageOfOrganizationsAllOfObject$`organizations`, "array[Organization]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`organizations`)) {
        sprintf(
        '"organizations":
        [%s]
',
        paste(sapply(self$`organizations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfOrganizationsAllOfJson) {
      PageOfOrganizationsAllOfObject <- jsonlite::fromJSON(PageOfOrganizationsAllOfJson)
      self$`organizations` <- ApiClient$new()$deserializeObj(PageOfOrganizationsAllOfObject$`organizations`, "array[Organization]", loadNamespace("openapi"))
      self
    }
  )
)
