# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfGrantsAllOf
#'
#' @description PageOfGrantsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field grants  list( \link{Grant} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfGrantsAllOf <- R6::R6Class(
  'PageOfGrantsAllOf',
  public = list(
    `grants` = NULL,
    initialize = function(
        `grants`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`grants`)) {
        stopifnot(is.vector(`grants`), length(`grants`) != 0)
        sapply(`grants`, function(x) stopifnot(R6::is.R6(x)))
        self$`grants` <- `grants`
      }
    },
    toJSON = function() {
      PageOfGrantsAllOfObject <- list()
      if (!is.null(self$`grants`)) {
        PageOfGrantsAllOfObject[['grants']] <-
          lapply(self$`grants`, function(x) x$toJSON())
      }

      PageOfGrantsAllOfObject
    },
    fromJSON = function(PageOfGrantsAllOfJson) {
      PageOfGrantsAllOfObject <- jsonlite::fromJSON(PageOfGrantsAllOfJson)
      if (!is.null(PageOfGrantsAllOfObject$`grants`)) {
        self$`grants` <- ApiClient$new()$deserializeObj(PageOfGrantsAllOfObject$`grants`, "array[Grant]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`grants`)) {
        sprintf(
        '"grants":
        [%s]
',
        paste(sapply(self$`grants`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfGrantsAllOfJson) {
      PageOfGrantsAllOfObject <- jsonlite::fromJSON(PageOfGrantsAllOfJson)
      self$`grants` <- ApiClient$new()$deserializeObj(PageOfGrantsAllOfObject$`grants`, "array[Grant]", loadNamespace("openapi"))
      self
    }
  )
)
