# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfOrgMembershipsAllOf
#'
#' @description PageOfOrgMembershipsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field orgMemberships  list( \link{OrgMembership} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfOrgMembershipsAllOf <- R6::R6Class(
  'PageOfOrgMembershipsAllOf',
  public = list(
    `orgMemberships` = NULL,
    initialize = function(
        `orgMemberships`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`orgMemberships`)) {
        stopifnot(is.vector(`orgMemberships`), length(`orgMemberships`) != 0)
        sapply(`orgMemberships`, function(x) stopifnot(R6::is.R6(x)))
        self$`orgMemberships` <- `orgMemberships`
      }
    },
    toJSON = function() {
      PageOfOrgMembershipsAllOfObject <- list()
      if (!is.null(self$`orgMemberships`)) {
        PageOfOrgMembershipsAllOfObject[['orgMemberships']] <-
          lapply(self$`orgMemberships`, function(x) x$toJSON())
      }

      PageOfOrgMembershipsAllOfObject
    },
    fromJSON = function(PageOfOrgMembershipsAllOfJson) {
      PageOfOrgMembershipsAllOfObject <- jsonlite::fromJSON(PageOfOrgMembershipsAllOfJson)
      if (!is.null(PageOfOrgMembershipsAllOfObject$`orgMemberships`)) {
        self$`orgMemberships` <- ApiClient$new()$deserializeObj(PageOfOrgMembershipsAllOfObject$`orgMemberships`, "array[OrgMembership]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`orgMemberships`)) {
        sprintf(
        '"orgMemberships":
        [%s]
',
        paste(sapply(self$`orgMemberships`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfOrgMembershipsAllOfJson) {
      PageOfOrgMembershipsAllOfObject <- jsonlite::fromJSON(PageOfOrgMembershipsAllOfJson)
      self$`orgMemberships` <- ApiClient$new()$deserializeObj(PageOfOrgMembershipsAllOfObject$`orgMemberships`, "array[OrgMembership]", loadNamespace("openapi"))
      self
    }
  )
)
