# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfTagsAllOf
#'
#' @description PageOfTagsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field tags  list( \link{Tag} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfTagsAllOf <- R6::R6Class(
  'PageOfTagsAllOf',
  public = list(
    `tags` = NULL,
    initialize = function(
        `tags`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(R6::is.R6(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      PageOfTagsAllOfObject <- list()
      if (!is.null(self$`tags`)) {
        PageOfTagsAllOfObject[['tags']] <-
          lapply(self$`tags`, function(x) x$toJSON())
      }

      PageOfTagsAllOfObject
    },
    fromJSON = function(PageOfTagsAllOfJson) {
      PageOfTagsAllOfObject <- jsonlite::fromJSON(PageOfTagsAllOfJson)
      if (!is.null(PageOfTagsAllOfObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(PageOfTagsAllOfObject$`tags`, "array[Tag]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
        [%s]
',
        paste(sapply(self$`tags`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfTagsAllOfJson) {
      PageOfTagsAllOfObject <- jsonlite::fromJSON(PageOfTagsAllOfJson)
      self$`tags` <- ApiClient$new()$deserializeObj(PageOfTagsAllOfObject$`tags`, "array[Tag]", loadNamespace("openapi"))
      self
    }
  )
)
