# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfChallengesAllOf
#'
#' @description PageOfChallengesAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field challenges  list( \link{Challenge} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfChallengesAllOf <- R6::R6Class(
  'PageOfChallengesAllOf',
  public = list(
    `challenges` = NULL,
    initialize = function(
        `challenges`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`challenges`)) {
        stopifnot(is.vector(`challenges`), length(`challenges`) != 0)
        sapply(`challenges`, function(x) stopifnot(R6::is.R6(x)))
        self$`challenges` <- `challenges`
      }
    },
    toJSON = function() {
      PageOfChallengesAllOfObject <- list()
      if (!is.null(self$`challenges`)) {
        PageOfChallengesAllOfObject[['challenges']] <-
          lapply(self$`challenges`, function(x) x$toJSON())
      }

      PageOfChallengesAllOfObject
    },
    fromJSON = function(PageOfChallengesAllOfJson) {
      PageOfChallengesAllOfObject <- jsonlite::fromJSON(PageOfChallengesAllOfJson)
      if (!is.null(PageOfChallengesAllOfObject$`challenges`)) {
        self$`challenges` <- ApiClient$new()$deserializeObj(PageOfChallengesAllOfObject$`challenges`, "array[Challenge]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`challenges`)) {
        sprintf(
        '"challenges":
        [%s]
',
        paste(sapply(self$`challenges`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfChallengesAllOfJson) {
      PageOfChallengesAllOfObject <- jsonlite::fromJSON(PageOfChallengesAllOfJson)
      self$`challenges` <- ApiClient$new()$deserializeObj(PageOfChallengesAllOfObject$`challenges`, "array[Challenge]", loadNamespace("openapi"))
      self
    }
  )
)
