# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfTags
#'
#' @description PageOfTags Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field tags  list( \link{Tag} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfTags <- R6::R6Class(
  'PageOfTags',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `tags` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `tags`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(R6::is.R6(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      PageOfTagsObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfTagsObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfTagsObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfTagsObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfTagsObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`tags`)) {
        PageOfTagsObject[['tags']] <-
          lapply(self$`tags`, function(x) x$toJSON())
      }

      PageOfTagsObject
    },
    fromJSON = function(PageOfTagsJson) {
      PageOfTagsObject <- jsonlite::fromJSON(PageOfTagsJson)
      if (!is.null(PageOfTagsObject$`offset`)) {
        self$`offset` <- PageOfTagsObject$`offset`
      }
      if (!is.null(PageOfTagsObject$`limit`)) {
        self$`limit` <- PageOfTagsObject$`limit`
      }
      if (!is.null(PageOfTagsObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfTagsObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfTagsObject$`totalResults`)) {
        self$`totalResults` <- PageOfTagsObject$`totalResults`
      }
      if (!is.null(PageOfTagsObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(PageOfTagsObject$`tags`, "array[Tag]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
        [%s]
',
        paste(sapply(self$`tags`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfTagsJson) {
      PageOfTagsObject <- jsonlite::fromJSON(PageOfTagsJson)
      self$`offset` <- PageOfTagsObject$`offset`
      self$`limit` <- PageOfTagsObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfTagsObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfTagsObject$`totalResults`
      self$`tags` <- ApiClient$new()$deserializeObj(PageOfTagsObject$`tags`, "array[Tag]", loadNamespace("openapi"))
      self
    }
  )
)
