# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfGrants
#'
#' @description PageOfGrants Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field grants  list( \link{Grant} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfGrants <- R6::R6Class(
  'PageOfGrants',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `grants` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `grants`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`grants`)) {
        stopifnot(is.vector(`grants`), length(`grants`) != 0)
        sapply(`grants`, function(x) stopifnot(R6::is.R6(x)))
        self$`grants` <- `grants`
      }
    },
    toJSON = function() {
      PageOfGrantsObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfGrantsObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfGrantsObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfGrantsObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfGrantsObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`grants`)) {
        PageOfGrantsObject[['grants']] <-
          lapply(self$`grants`, function(x) x$toJSON())
      }

      PageOfGrantsObject
    },
    fromJSON = function(PageOfGrantsJson) {
      PageOfGrantsObject <- jsonlite::fromJSON(PageOfGrantsJson)
      if (!is.null(PageOfGrantsObject$`offset`)) {
        self$`offset` <- PageOfGrantsObject$`offset`
      }
      if (!is.null(PageOfGrantsObject$`limit`)) {
        self$`limit` <- PageOfGrantsObject$`limit`
      }
      if (!is.null(PageOfGrantsObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfGrantsObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfGrantsObject$`totalResults`)) {
        self$`totalResults` <- PageOfGrantsObject$`totalResults`
      }
      if (!is.null(PageOfGrantsObject$`grants`)) {
        self$`grants` <- ApiClient$new()$deserializeObj(PageOfGrantsObject$`grants`, "array[Grant]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`grants`)) {
        sprintf(
        '"grants":
        [%s]
',
        paste(sapply(self$`grants`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfGrantsJson) {
      PageOfGrantsObject <- jsonlite::fromJSON(PageOfGrantsJson)
      self$`offset` <- PageOfGrantsObject$`offset`
      self$`limit` <- PageOfGrantsObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfGrantsObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfGrantsObject$`totalResults`
      self$`grants` <- ApiClient$new()$deserializeObj(PageOfGrantsObject$`grants`, "array[Grant]", loadNamespace("openapi"))
      self
    }
  )
)
