# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfUsers
#'
#' @description PageOfUsers Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field users  list( \link{User} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfUsers <- R6::R6Class(
  'PageOfUsers',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `users` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `users`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`users`)) {
        stopifnot(is.vector(`users`), length(`users`) != 0)
        sapply(`users`, function(x) stopifnot(R6::is.R6(x)))
        self$`users` <- `users`
      }
    },
    toJSON = function() {
      PageOfUsersObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfUsersObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfUsersObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfUsersObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfUsersObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`users`)) {
        PageOfUsersObject[['users']] <-
          lapply(self$`users`, function(x) x$toJSON())
      }

      PageOfUsersObject
    },
    fromJSON = function(PageOfUsersJson) {
      PageOfUsersObject <- jsonlite::fromJSON(PageOfUsersJson)
      if (!is.null(PageOfUsersObject$`offset`)) {
        self$`offset` <- PageOfUsersObject$`offset`
      }
      if (!is.null(PageOfUsersObject$`limit`)) {
        self$`limit` <- PageOfUsersObject$`limit`
      }
      if (!is.null(PageOfUsersObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfUsersObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfUsersObject$`totalResults`)) {
        self$`totalResults` <- PageOfUsersObject$`totalResults`
      }
      if (!is.null(PageOfUsersObject$`users`)) {
        self$`users` <- ApiClient$new()$deserializeObj(PageOfUsersObject$`users`, "array[User]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`users`)) {
        sprintf(
        '"users":
        [%s]
',
        paste(sapply(self$`users`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfUsersJson) {
      PageOfUsersObject <- jsonlite::fromJSON(PageOfUsersJson)
      self$`offset` <- PageOfUsersObject$`offset`
      self$`limit` <- PageOfUsersObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfUsersObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfUsersObject$`totalResults`
      self$`users` <- ApiClient$new()$deserializeObj(PageOfUsersObject$`users`, "array[User]", loadNamespace("openapi"))
      self
    }
  )
)
