# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfChallengePlatforms
#'
#' @description PageOfChallengePlatforms Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field challengePlatforms  list( \link{ChallengePlatform} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfChallengePlatforms <- R6::R6Class(
  'PageOfChallengePlatforms',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `challengePlatforms` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `challengePlatforms`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`challengePlatforms`)) {
        stopifnot(is.vector(`challengePlatforms`), length(`challengePlatforms`) != 0)
        sapply(`challengePlatforms`, function(x) stopifnot(R6::is.R6(x)))
        self$`challengePlatforms` <- `challengePlatforms`
      }
    },
    toJSON = function() {
      PageOfChallengePlatformsObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfChallengePlatformsObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfChallengePlatformsObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfChallengePlatformsObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfChallengePlatformsObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`challengePlatforms`)) {
        PageOfChallengePlatformsObject[['challengePlatforms']] <-
          lapply(self$`challengePlatforms`, function(x) x$toJSON())
      }

      PageOfChallengePlatformsObject
    },
    fromJSON = function(PageOfChallengePlatformsJson) {
      PageOfChallengePlatformsObject <- jsonlite::fromJSON(PageOfChallengePlatformsJson)
      if (!is.null(PageOfChallengePlatformsObject$`offset`)) {
        self$`offset` <- PageOfChallengePlatformsObject$`offset`
      }
      if (!is.null(PageOfChallengePlatformsObject$`limit`)) {
        self$`limit` <- PageOfChallengePlatformsObject$`limit`
      }
      if (!is.null(PageOfChallengePlatformsObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfChallengePlatformsObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfChallengePlatformsObject$`totalResults`)) {
        self$`totalResults` <- PageOfChallengePlatformsObject$`totalResults`
      }
      if (!is.null(PageOfChallengePlatformsObject$`challengePlatforms`)) {
        self$`challengePlatforms` <- ApiClient$new()$deserializeObj(PageOfChallengePlatformsObject$`challengePlatforms`, "array[ChallengePlatform]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`challengePlatforms`)) {
        sprintf(
        '"challengePlatforms":
        [%s]
',
        paste(sapply(self$`challengePlatforms`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfChallengePlatformsJson) {
      PageOfChallengePlatformsObject <- jsonlite::fromJSON(PageOfChallengePlatformsJson)
      self$`offset` <- PageOfChallengePlatformsObject$`offset`
      self$`limit` <- PageOfChallengePlatformsObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfChallengePlatformsObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfChallengePlatformsObject$`totalResults`
      self$`challengePlatforms` <- ApiClient$new()$deserializeObj(PageOfChallengePlatformsObject$`challengePlatforms`, "array[ChallengePlatform]", loadNamespace("openapi"))
      self
    }
  )
)
