# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfChallenges
#'
#' @description PageOfChallenges Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field challenges  list( \link{Challenge} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfChallenges <- R6::R6Class(
  'PageOfChallenges',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `challenges` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `challenges`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`challenges`)) {
        stopifnot(is.vector(`challenges`), length(`challenges`) != 0)
        sapply(`challenges`, function(x) stopifnot(R6::is.R6(x)))
        self$`challenges` <- `challenges`
      }
    },
    toJSON = function() {
      PageOfChallengesObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfChallengesObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfChallengesObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfChallengesObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfChallengesObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`challenges`)) {
        PageOfChallengesObject[['challenges']] <-
          lapply(self$`challenges`, function(x) x$toJSON())
      }

      PageOfChallengesObject
    },
    fromJSON = function(PageOfChallengesJson) {
      PageOfChallengesObject <- jsonlite::fromJSON(PageOfChallengesJson)
      if (!is.null(PageOfChallengesObject$`offset`)) {
        self$`offset` <- PageOfChallengesObject$`offset`
      }
      if (!is.null(PageOfChallengesObject$`limit`)) {
        self$`limit` <- PageOfChallengesObject$`limit`
      }
      if (!is.null(PageOfChallengesObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfChallengesObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfChallengesObject$`totalResults`)) {
        self$`totalResults` <- PageOfChallengesObject$`totalResults`
      }
      if (!is.null(PageOfChallengesObject$`challenges`)) {
        self$`challenges` <- ApiClient$new()$deserializeObj(PageOfChallengesObject$`challenges`, "array[Challenge]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`challenges`)) {
        sprintf(
        '"challenges":
        [%s]
',
        paste(sapply(self$`challenges`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfChallengesJson) {
      PageOfChallengesObject <- jsonlite::fromJSON(PageOfChallengesJson)
      self$`offset` <- PageOfChallengesObject$`offset`
      self$`limit` <- PageOfChallengesObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfChallengesObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfChallengesObject$`totalResults`
      self$`challenges` <- ApiClient$new()$deserializeObj(PageOfChallengesObject$`challenges`, "array[Challenge]", loadNamespace("openapi"))
      self
    }
  )
)
