# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PageOfOrgMemberships
#'
#' @description PageOfOrgMemberships Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @field orgMemberships  list( \link{OrgMembership} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfOrgMemberships <- R6::R6Class(
  'PageOfOrgMemberships',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    `orgMemberships` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, `orgMemberships`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
      if (!missing(`orgMemberships`)) {
        stopifnot(is.vector(`orgMemberships`), length(`orgMemberships`) != 0)
        sapply(`orgMemberships`, function(x) stopifnot(R6::is.R6(x)))
        self$`orgMemberships` <- `orgMemberships`
      }
    },
    toJSON = function() {
      PageOfOrgMembershipsObject <- list()
      if (!is.null(self$`offset`)) {
        PageOfOrgMembershipsObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        PageOfOrgMembershipsObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        PageOfOrgMembershipsObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        PageOfOrgMembershipsObject[['totalResults']] <-
          self$`totalResults`
      }
      if (!is.null(self$`orgMemberships`)) {
        PageOfOrgMembershipsObject[['orgMemberships']] <-
          lapply(self$`orgMemberships`, function(x) x$toJSON())
      }

      PageOfOrgMembershipsObject
    },
    fromJSON = function(PageOfOrgMembershipsJson) {
      PageOfOrgMembershipsObject <- jsonlite::fromJSON(PageOfOrgMembershipsJson)
      if (!is.null(PageOfOrgMembershipsObject$`offset`)) {
        self$`offset` <- PageOfOrgMembershipsObject$`offset`
      }
      if (!is.null(PageOfOrgMembershipsObject$`limit`)) {
        self$`limit` <- PageOfOrgMembershipsObject$`limit`
      }
      if (!is.null(PageOfOrgMembershipsObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(PageOfOrgMembershipsObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(PageOfOrgMembershipsObject$`totalResults`)) {
        self$`totalResults` <- PageOfOrgMembershipsObject$`totalResults`
      }
      if (!is.null(PageOfOrgMembershipsObject$`orgMemberships`)) {
        self$`orgMemberships` <- ApiClient$new()$deserializeObj(PageOfOrgMembershipsObject$`orgMemberships`, "array[OrgMembership]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )},
        if (!is.null(self$`orgMemberships`)) {
        sprintf(
        '"orgMemberships":
        [%s]
',
        paste(sapply(self$`orgMemberships`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PageOfOrgMembershipsJson) {
      PageOfOrgMembershipsObject <- jsonlite::fromJSON(PageOfOrgMembershipsJson)
      self$`offset` <- PageOfOrgMembershipsObject$`offset`
      self$`limit` <- PageOfOrgMembershipsObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(PageOfOrgMembershipsObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- PageOfOrgMembershipsObject$`totalResults`
      self$`orgMemberships` <- ApiClient$new()$deserializeObj(PageOfOrgMembershipsObject$`orgMemberships`, "array[OrgMembership]", loadNamespace("openapi"))
      self
    }
  )
)
