# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ResponsePageMetadataPaging
#'
#' @description ResponsePageMetadataPaging Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field next  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponsePageMetadataPaging <- R6::R6Class(
  'ResponsePageMetadataPaging',
  public = list(
    `next` = NULL,
    initialize = function(
        `next`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`next`)) {
        stopifnot(is.character(`next`), length(`next`) == 1)
        self$`next` <- `next`
      }
    },
    toJSON = function() {
      ResponsePageMetadataPagingObject <- list()
      if (!is.null(self$`next`)) {
        ResponsePageMetadataPagingObject[['next']] <-
          self$`next`
      }

      ResponsePageMetadataPagingObject
    },
    fromJSON = function(ResponsePageMetadataPagingJson) {
      ResponsePageMetadataPagingObject <- jsonlite::fromJSON(ResponsePageMetadataPagingJson)
      if (!is.null(ResponsePageMetadataPagingObject$`next`)) {
        self$`next` <- ResponsePageMetadataPagingObject$`next`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`next`)) {
        sprintf(
        '"next":
          "%s"
                ',
        self$`next`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ResponsePageMetadataPagingJson) {
      ResponsePageMetadataPagingObject <- jsonlite::fromJSON(ResponsePageMetadataPagingJson)
      self$`next` <- ResponsePageMetadataPagingObject$`next`
      self
    }
  )
)
