# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ResponsePageMetadata
#'
#' @description ResponsePageMetadata Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field offset  integer 
#'
#' @field limit  integer 
#'
#' @field paging  \link{ResponsePageMetadataPaging} 
#'
#' @field totalResults  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponsePageMetadata <- R6::R6Class(
  'ResponsePageMetadata',
  public = list(
    `offset` = NULL,
    `limit` = NULL,
    `paging` = NULL,
    `totalResults` = NULL,
    initialize = function(
        `offset`, `limit`, `paging`, `totalResults`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!missing(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!missing(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!missing(`totalResults`)) {
        stopifnot(is.numeric(`totalResults`), length(`totalResults`) == 1)
        self$`totalResults` <- `totalResults`
      }
    },
    toJSON = function() {
      ResponsePageMetadataObject <- list()
      if (!is.null(self$`offset`)) {
        ResponsePageMetadataObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        ResponsePageMetadataObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`paging`)) {
        ResponsePageMetadataObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`totalResults`)) {
        ResponsePageMetadataObject[['totalResults']] <-
          self$`totalResults`
      }

      ResponsePageMetadataObject
    },
    fromJSON = function(ResponsePageMetadataJson) {
      ResponsePageMetadataObject <- jsonlite::fromJSON(ResponsePageMetadataJson)
      if (!is.null(ResponsePageMetadataObject$`offset`)) {
        self$`offset` <- ResponsePageMetadataObject$`offset`
      }
      if (!is.null(ResponsePageMetadataObject$`limit`)) {
        self$`limit` <- ResponsePageMetadataObject$`limit`
      }
      if (!is.null(ResponsePageMetadataObject$`paging`)) {
        pagingObject <- ResponsePageMetadataPaging$new()
        pagingObject$fromJSON(jsonlite::toJSON(ResponsePageMetadataObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(ResponsePageMetadataObject$`totalResults`)) {
        self$`totalResults` <- ResponsePageMetadataObject$`totalResults`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`totalResults`)) {
        sprintf(
        '"totalResults":
          %d
                ',
        self$`totalResults`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ResponsePageMetadataJson) {
      ResponsePageMetadataObject <- jsonlite::fromJSON(ResponsePageMetadataJson)
      self$`offset` <- ResponsePageMetadataObject$`offset`
      self$`limit` <- ResponsePageMetadataObject$`limit`
      self$`paging` <- ResponsePageMetadataPaging$new()$fromJSON(jsonlite::toJSON(ResponsePageMetadataObject$paging, auto_unbox = TRUE, digits = NA))
      self$`totalResults` <- ResponsePageMetadataObject$`totalResults`
      self
    }
  )
)
