# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Tag
#'
#' @description Tag Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field name  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Tag <- R6::R6Class(
  'Tag',
  public = list(
    `id` = NULL,
    `name` = NULL,
    initialize = function(
        `id`, `name`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      TagObject <- list()
      if (!is.null(self$`id`)) {
        TagObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        TagObject[['name']] <-
          self$`name`
      }

      TagObject
    },
    fromJSON = function(TagJson) {
      TagObject <- jsonlite::fromJSON(TagJson)
      if (!is.null(TagObject$`id`)) {
        self$`id` <- TagObject$`id`
      }
      if (!is.null(TagObject$`name`)) {
        self$`name` <- TagObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TagJson) {
      TagObject <- jsonlite::fromJSON(TagJson)
      self$`id` <- TagObject$`id`
      self$`name` <- TagObject$`name`
      self
    }
  )
)
