# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TagCreateRequest
#'
#' @description TagCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TagCreateRequest <- R6::R6Class(
  'TagCreateRequest',
  public = list(
    `name` = NULL,
    initialize = function(
        `name`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      TagCreateRequestObject <- list()
      if (!is.null(self$`name`)) {
        TagCreateRequestObject[['name']] <-
          self$`name`
      }

      TagCreateRequestObject
    },
    fromJSON = function(TagCreateRequestJson) {
      TagCreateRequestObject <- jsonlite::fromJSON(TagCreateRequestJson)
      if (!is.null(TagCreateRequestObject$`name`)) {
        self$`name` <- TagCreateRequestObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TagCreateRequestJson) {
      TagCreateRequestObject <- jsonlite::fromJSON(TagCreateRequestJson)
      self$`name` <- TagCreateRequestObject$`name`
      self
    }
  )
)
