# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TagCreateResponse
#'
#' @description TagCreateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TagCreateResponse <- R6::R6Class(
  'TagCreateResponse',
  public = list(
    `id` = NULL,
    initialize = function(
        `id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      TagCreateResponseObject <- list()
      if (!is.null(self$`id`)) {
        TagCreateResponseObject[['id']] <-
          self$`id`
      }

      TagCreateResponseObject
    },
    fromJSON = function(TagCreateResponseJson) {
      TagCreateResponseObject <- jsonlite::fromJSON(TagCreateResponseJson)
      if (!is.null(TagCreateResponseObject$`id`)) {
        self$`id` <- TagCreateResponseObject$`id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TagCreateResponseJson) {
      TagCreateResponseObject <- jsonlite::fromJSON(TagCreateResponseJson)
      self$`id` <- TagCreateResponseObject$`id`
      self
    }
  )
)
