# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title User
#'
#' @description User Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field login  character 
#'
#' @field email  character 
#'
#' @field name  character [optional]
#'
#' @field avatarUrl  character [optional]
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @field type  character 
#'
#' @field bio  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
User <- R6::R6Class(
  'User',
  public = list(
    `id` = NULL,
    `login` = NULL,
    `email` = NULL,
    `name` = NULL,
    `avatarUrl` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    `type` = NULL,
    `bio` = NULL,
    initialize = function(
        `id`, `login`, `email`, `createdAt`, `updatedAt`, `type`, `name`=NULL, `avatarUrl`=NULL, `bio`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
      if (!is.null(`bio`)) {
        stopifnot(is.character(`bio`), length(`bio`) == 1)
        self$`bio` <- `bio`
      }
    },
    toJSON = function() {
      UserObject <- list()
      if (!is.null(self$`id`)) {
        UserObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`login`)) {
        UserObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`email`)) {
        UserObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`name`)) {
        UserObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`avatarUrl`)) {
        UserObject[['avatarUrl']] <-
          self$`avatarUrl`
      }
      if (!is.null(self$`createdAt`)) {
        UserObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        UserObject[['updatedAt']] <-
          self$`updatedAt`
      }
      if (!is.null(self$`type`)) {
        UserObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`bio`)) {
        UserObject[['bio']] <-
          self$`bio`
      }

      UserObject
    },
    fromJSON = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      if (!is.null(UserObject$`id`)) {
        self$`id` <- UserObject$`id`
      }
      if (!is.null(UserObject$`login`)) {
        self$`login` <- UserObject$`login`
      }
      if (!is.null(UserObject$`email`)) {
        self$`email` <- UserObject$`email`
      }
      if (!is.null(UserObject$`name`)) {
        self$`name` <- UserObject$`name`
      }
      if (!is.null(UserObject$`avatarUrl`)) {
        self$`avatarUrl` <- UserObject$`avatarUrl`
      }
      if (!is.null(UserObject$`createdAt`)) {
        self$`createdAt` <- UserObject$`createdAt`
      }
      if (!is.null(UserObject$`updatedAt`)) {
        self$`updatedAt` <- UserObject$`updatedAt`
      }
      if (!is.null(UserObject$`type`)) {
        self$`type` <- UserObject$`type`
      }
      if (!is.null(UserObject$`bio`)) {
        self$`bio` <- UserObject$`bio`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`bio`)) {
        sprintf(
        '"bio":
          "%s"
                ',
        self$`bio`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      self$`id` <- UserObject$`id`
      self$`login` <- UserObject$`login`
      self$`email` <- UserObject$`email`
      self$`name` <- UserObject$`name`
      self$`avatarUrl` <- UserObject$`avatarUrl`
      self$`createdAt` <- UserObject$`createdAt`
      self$`updatedAt` <- UserObject$`updatedAt`
      self$`type` <- UserObject$`type`
      self$`bio` <- UserObject$`bio`
      self
    }
  )
)
