# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title User operations
#' @description openapi.User
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateUser } \emph{ Create a user }
#' Create a user with the specified account name
#'
#' \itemize{
#' \item \emph{ @param } user.create.request \link{UserCreateRequest}
#' \item \emph{ @returnType } \link{UserCreateResponse} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : UserCreateResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteAllUsers } \emph{ Delete all users }
#' Delete all users
#'
#' \itemize{
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteUser } \emph{ Delete a user }
#' Deletes the user specified
#'
#' \itemize{
#' \item \emph{ @param } user.id character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetAuthenticatedUser } \emph{ Get the authenticated user }
#' Get the authenticated user
#'
#' \itemize{
#' \item \emph{ @returnType } \link{User} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : User 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetUser } \emph{ Get a user }
#' Returns the user specified
#'
#' \itemize{
#' \item \emph{ @param } user.id character
#' \item \emph{ @returnType } \link{User} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : User 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ IsStarredChallenge } \emph{ Check if a challenge is starred by the authenticated user }
#' Check if a challenge is starred by the authenticated user
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#'
#'
#' \item status code : 200 | Response if this challenge is starred by you
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListAuthenticatedUserOrganizations } \emph{ List organizations of the authenticated user }
#' Lists organizations the authenticated user belongs to.
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfOrganizations} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfOrganizations 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListStarredChallenges } \emph{ List challenges starred by the authenticated user }
#' Lists challenges the authenticated user has starred.
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfChallenges} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfChallenges 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListUserOrganizations } \emph{ List orgsnizations of a user }
#' Lists organizations a user belongs to.
#'
#' \itemize{
#' \item \emph{ @param } user.id character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfOrganizations} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfOrganizations 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListUserStarredChallenges } \emph{ List challenges starred by a user }
#' Lists challenges a user has starred.
#'
#' \itemize{
#' \item \emph{ @param } user.id character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfChallenges} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfChallenges 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListUsers } \emph{ Get all users }
#' Returns the users
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PageOfUsers} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PageOfUsers 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ StarChallenge } \emph{ Star a challenge for the authenticated user }
#' Star a challenge for the authenticated user
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The request conflicts with current state of the target resource
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UnstarChallenge } \emph{ Unstar a challenge for the authenticated user }
#' Unstar a challenge for the authenticated user
#'
#' \itemize{
#' \item \emph{ @param } account.name character
#' \item \emph{ @param } challenge.name character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The specified resource was not found
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateUser  ####################
#'
#' library(openapi)
#' var.user.create.request <- UserCreateRequest$new() # UserCreateRequest | 
#'
#' #Create a user
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$CreateUser(var.user.create.request)
#'
#'
#' ####################  DeleteAllUsers  ####################
#'
#' library(openapi)
#'
#' #Delete all users
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$DeleteAllUsers()
#'
#'
#' ####################  DeleteUser  ####################
#'
#' library(openapi)
#' var.user.id <- 'user.id_example' # character | The unique identifier of the user, either the user account ID or login
#'
#' #Delete a user
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$DeleteUser(var.user.id)
#'
#'
#' ####################  GetAuthenticatedUser  ####################
#'
#' library(openapi)
#'
#' #Get the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetAuthenticatedUser()
#'
#'
#' ####################  GetUser  ####################
#'
#' library(openapi)
#' var.user.id <- 'user.id_example' # character | The unique identifier of the user, either the user account ID or login
#'
#' #Get a user
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$GetUser(var.user.id)
#'
#'
#' ####################  IsStarredChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Check if a challenge is starred by the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$IsStarredChallenge(var.account.name, var.challenge.name)
#'
#'
#' ####################  ListAuthenticatedUserOrganizations  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List organizations of the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$ListAuthenticatedUserOrganizations(limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListStarredChallenges  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List challenges starred by the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$ListStarredChallenges(limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListUserOrganizations  ####################
#'
#' library(openapi)
#' var.user.id <- 'user.id_example' # character | The unique identifier of the user, either the user account ID or login
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List orgsnizations of a user
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$ListUserOrganizations(var.user.id, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListUserStarredChallenges  ####################
#'
#' library(openapi)
#' var.user.id <- 'user.id_example' # character | The unique identifier of the user, either the user account ID or login
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #List challenges starred by a user
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$ListUserStarredChallenges(var.user.id, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListUsers  ####################
#'
#' library(openapi)
#' var.limit <- 10 # integer | Maximum number of results returned
#' var.offset <- 0 # integer | Index of the first result that must be returned
#'
#' #Get all users
#' api.instance <- UserApi$new()
#'
#' result <- api.instance$ListUsers(limit=var.limit, offset=var.offset)
#'
#'
#' ####################  StarChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Star a challenge for the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$StarChallenge(var.account.name, var.challenge.name)
#'
#'
#' ####################  UnstarChallenge  ####################
#'
#' library(openapi)
#' var.account.name <- 'account.name_example' # character | The name of the account that owns the challenge
#' var.challenge.name <- 'challenge.name_example' # character | The name of the challenge
#'
#' #Unstar a challenge for the authenticated user
#' api.instance <- UserApi$new()
#'
#' #Configure HTTP basic authorization: BearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$UnstarChallenge(var.account.name, var.challenge.name)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
UserApi <- R6::R6Class(
  'UserApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    CreateUser = function(user.create.request, ...){
      apiResponse <- self$CreateUserWithHttpInfo(user.create.request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateUserWithHttpInfo = function(user.create.request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.create.request`)) {
        stop("Missing required parameter `user.create.request`.")
      }

      if (!missing(`user.create.request`)) {
        body <- `user.create.request`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/users"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "UserCreateResponse", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteAllUsers = function(...){
      apiResponse <- self$DeleteAllUsersWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteAllUsersWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/users"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteUser = function(user.id, ...){
      apiResponse <- self$DeleteUserWithHttpInfo(user.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteUserWithHttpInfo = function(user.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.id`)) {
        stop("Missing required parameter `user.id`.")
      }

      body <- NULL
      urlPath <- "/users/{userId}"
      if (!missing(`user.id`)) {
        urlPath <- gsub(paste0("\\{", "userId", "\\}"), URLencode(as.character(`user.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetAuthenticatedUser = function(...){
      apiResponse <- self$GetAuthenticatedUserWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetAuthenticatedUserWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/user"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "User", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetUser = function(user.id, ...){
      apiResponse <- self$GetUserWithHttpInfo(user.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetUserWithHttpInfo = function(user.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.id`)) {
        stop("Missing required parameter `user.id`.")
      }

      body <- NULL
      urlPath <- "/users/{userId}"
      if (!missing(`user.id`)) {
        urlPath <- gsub(paste0("\\{", "userId", "\\}"), URLencode(as.character(`user.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "User", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    IsStarredChallenge = function(account.name, challenge.name, ...){
      apiResponse <- self$IsStarredChallengeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    IsStarredChallengeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/user/starred/{accountName}/{challengeName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListAuthenticatedUserOrganizations = function(limit=10, offset=0, ...){
      apiResponse <- self$ListAuthenticatedUserOrganizationsWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListAuthenticatedUserOrganizationsWithHttpInfo = function(limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/user/orgs"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfOrganizations", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListStarredChallenges = function(limit=10, offset=0, ...){
      apiResponse <- self$ListStarredChallengesWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListStarredChallengesWithHttpInfo = function(limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/user/starred"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfChallenges", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListUserOrganizations = function(user.id, limit=10, offset=0, ...){
      apiResponse <- self$ListUserOrganizationsWithHttpInfo(user.id, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListUserOrganizationsWithHttpInfo = function(user.id, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.id`)) {
        stop("Missing required parameter `user.id`.")
      }

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/users/{userId}/orgs"
      if (!missing(`user.id`)) {
        urlPath <- gsub(paste0("\\{", "userId", "\\}"), URLencode(as.character(`user.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfOrganizations", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListUserStarredChallenges = function(user.id, limit=10, offset=0, ...){
      apiResponse <- self$ListUserStarredChallengesWithHttpInfo(user.id, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListUserStarredChallengesWithHttpInfo = function(user.id, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.id`)) {
        stop("Missing required parameter `user.id`.")
      }

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/users/{userId}/starred"
      if (!missing(`user.id`)) {
        urlPath <- gsub(paste0("\\{", "userId", "\\}"), URLencode(as.character(`user.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfChallenges", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListUsers = function(limit=10, offset=0, ...){
      apiResponse <- self$ListUsersWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListUsersWithHttpInfo = function(limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/users"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PageOfUsers", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    StarChallenge = function(account.name, challenge.name, ...){
      apiResponse <- self$StarChallengeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    StarChallengeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/user/starred/{accountName}/{challengeName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UnstarChallenge = function(account.name, challenge.name, ...){
      apiResponse <- self$UnstarChallengeWithHttpInfo(account.name, challenge.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UnstarChallengeWithHttpInfo = function(account.name, challenge.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`account.name`)) {
        stop("Missing required parameter `account.name`.")
      }

      if (missing(`challenge.name`)) {
        stop("Missing required parameter `challenge.name`.")
      }

      body <- NULL
      urlPath <- "/user/starred/{accountName}/{challengeName}"
      if (!missing(`account.name`)) {
        urlPath <- gsub(paste0("\\{", "accountName", "\\}"), URLencode(as.character(`account.name`), reserved = TRUE), urlPath)
      }

      if (!missing(`challenge.name`)) {
        urlPath <- gsub(paste0("\\{", "challengeName", "\\}"), URLencode(as.character(`challenge.name`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "object", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
