# Registry of Open Community Challenges API
#
# The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
#
# The version of the OpenAPI document: 0.5.0
# Contact: thomas.schaffter@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UserAllOf
#'
#' @description UserAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field login  character 
#'
#' @field email  character 
#'
#' @field name  character [optional]
#'
#' @field avatarUrl  character [optional]
#'
#' @field createdAt  character 
#'
#' @field updatedAt  character 
#'
#' @field type  character 
#'
#' @field bio  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserAllOf <- R6::R6Class(
  'UserAllOf',
  public = list(
    `login` = NULL,
    `email` = NULL,
    `name` = NULL,
    `avatarUrl` = NULL,
    `createdAt` = NULL,
    `updatedAt` = NULL,
    `type` = NULL,
    `bio` = NULL,
    initialize = function(
        `login`, `email`, `createdAt`, `updatedAt`, `type`, `name`=NULL, `avatarUrl`=NULL, `bio`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`login`)) {
        stopifnot(is.character(`login`), length(`login`) == 1)
        self$`login` <- `login`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`updatedAt`)) {
        stopifnot(is.character(`updatedAt`), length(`updatedAt`) == 1)
        self$`updatedAt` <- `updatedAt`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`avatarUrl`)) {
        stopifnot(is.character(`avatarUrl`), length(`avatarUrl`) == 1)
        self$`avatarUrl` <- `avatarUrl`
      }
      if (!is.null(`bio`)) {
        stopifnot(is.character(`bio`), length(`bio`) == 1)
        self$`bio` <- `bio`
      }
    },
    toJSON = function() {
      UserAllOfObject <- list()
      if (!is.null(self$`login`)) {
        UserAllOfObject[['login']] <-
          self$`login`
      }
      if (!is.null(self$`email`)) {
        UserAllOfObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`name`)) {
        UserAllOfObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`avatarUrl`)) {
        UserAllOfObject[['avatarUrl']] <-
          self$`avatarUrl`
      }
      if (!is.null(self$`createdAt`)) {
        UserAllOfObject[['createdAt']] <-
          self$`createdAt`
      }
      if (!is.null(self$`updatedAt`)) {
        UserAllOfObject[['updatedAt']] <-
          self$`updatedAt`
      }
      if (!is.null(self$`type`)) {
        UserAllOfObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`bio`)) {
        UserAllOfObject[['bio']] <-
          self$`bio`
      }

      UserAllOfObject
    },
    fromJSON = function(UserAllOfJson) {
      UserAllOfObject <- jsonlite::fromJSON(UserAllOfJson)
      if (!is.null(UserAllOfObject$`login`)) {
        self$`login` <- UserAllOfObject$`login`
      }
      if (!is.null(UserAllOfObject$`email`)) {
        self$`email` <- UserAllOfObject$`email`
      }
      if (!is.null(UserAllOfObject$`name`)) {
        self$`name` <- UserAllOfObject$`name`
      }
      if (!is.null(UserAllOfObject$`avatarUrl`)) {
        self$`avatarUrl` <- UserAllOfObject$`avatarUrl`
      }
      if (!is.null(UserAllOfObject$`createdAt`)) {
        self$`createdAt` <- UserAllOfObject$`createdAt`
      }
      if (!is.null(UserAllOfObject$`updatedAt`)) {
        self$`updatedAt` <- UserAllOfObject$`updatedAt`
      }
      if (!is.null(UserAllOfObject$`type`)) {
        self$`type` <- UserAllOfObject$`type`
      }
      if (!is.null(UserAllOfObject$`bio`)) {
        self$`bio` <- UserAllOfObject$`bio`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`login`)) {
        sprintf(
        '"login":
          "%s"
                ',
        self$`login`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`avatarUrl`)) {
        sprintf(
        '"avatarUrl":
          "%s"
                ',
        self$`avatarUrl`
        )},
        if (!is.null(self$`createdAt`)) {
        sprintf(
        '"createdAt":
          "%s"
                ',
        self$`createdAt`
        )},
        if (!is.null(self$`updatedAt`)) {
        sprintf(
        '"updatedAt":
          "%s"
                ',
        self$`updatedAt`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`bio`)) {
        sprintf(
        '"bio":
          "%s"
                ',
        self$`bio`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UserAllOfJson) {
      UserAllOfObject <- jsonlite::fromJSON(UserAllOfJson)
      self$`login` <- UserAllOfObject$`login`
      self$`email` <- UserAllOfObject$`email`
      self$`name` <- UserAllOfObject$`name`
      self$`avatarUrl` <- UserAllOfObject$`avatarUrl`
      self$`createdAt` <- UserAllOfObject$`createdAt`
      self$`updatedAt` <- UserAllOfObject$`updatedAt`
      self$`type` <- UserAllOfObject$`type`
      self$`bio` <- UserAllOfObject$`bio`
      self
    }
  )
)
